/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type XijingPageAddRequest struct {
	AccountId    *int64                  `json:"account_id,omitempty"`
	IsAutoSubmit *int64                  `json:"is_auto_submit,omitempty"`
	Pages        *[]ComponentPagesStruct `json:"pages,omitempty"`
}
