/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// PayStatus : 书籍的付费状态
type PayStatus string

// List of PayStatus
const (
	PayStatus_FREE   PayStatus = "PAY_STATUS_FREE"
	PayStatus_PAID   PayStatus = "PAY_STATUS_PAID"
	PayStatus_MEMBER PayStatus = "PAY_STATUS_MEMBER"
)
