/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 身份证明
type IndividualQualification struct {
	Name                 *string `json:"name,omitempty"`
	IdentificationNumber *string `json:"identification_number,omitempty"`
}
