/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// AdCreativeSource : 创意来源
type AdCreativeSource string

// List of AdCreativeSource
const (
	AdCreativeSource_SOURCE_NORMAL                        AdCreativeSource = "AD_CREATIVE_SOURCE_NORMAL"
	AdCreativeSource_AUTO_DERIVE                          AdCreativeSource = "AD_CREATIVE_AUTO_DERIVE"
	AdCreativeSource_AUTO_GENERATE                        AdCreativeSource = "AD_CREATIVE_AUTO_GENERATE"
	AdCreativeSource_PAGE_DERIVE                          AdCreativeSource = "AD_CREATIVE_PAGE_DERIVE"
	AdCreativeSource_SEARCH_EXPANSION                     AdCreativeSource = "AD_CREATIVE_SEARCH_EXPANSION"
	AdCreativeSource_INTEREST_GENERATE                    AdCreativeSource = "AD_CREATIVE_INTEREST_GENERATE"
	AdCreativeSource_SPECIFIC_COMBINATION                 AdCreativeSource = "AD_CREATIVE_SPECIFIC_COMBINATION"
	AdCreativeSource_SMART_DELIVERY_MARKETING_TARGET_AIGC AdCreativeSource = "AD_CREATIVE_SMART_DELIVERY_MARKETING_TARGET_AIGC"
	AdCreativeSource_HISTORY_COMP_REUSE                   AdCreativeSource = "AD_CREATIVE_HISTORY_COMP_REUSE"
)
