/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// MarketingAssetType : 产品类型
type MarketingAssetType string

// List of MarketingAssetType
const (
	MarketingAssetType_UNKNOWN                                    MarketingAssetType = "MARKETING_ASSET_TYPE_UNKNOWN"
	MarketingAssetType_TRAFFIC_CAR_BRAND                          MarketingAssetType = "MARKETING_ASSET_TYPE_TRAFFIC_CAR_BRAND"
	MarketingAssetType_TRAFFIC_CAR_SERIES                         MarketingAssetType = "MARKETING_ASSET_TYPE_TRAFFIC_CAR_SERIES"
	MarketingAssetType_TRAFFIC_CAR_MODEL                          MarketingAssetType = "MARKETING_ASSET_TYPE_TRAFFIC_CAR_MODEL"
	MarketingAssetType_CONSUME_MEDICAL_SERVICE                    MarketingAssetType = "MARKETING_ASSET_TYPE_CONSUME_MEDICAL_SERVICE"
	MarketingAssetType_TOURIST_ATTRACTIONS_TICKETS_TICKET_PACKAGE MarketingAssetType = "MARKETING_ASSET_TYPE_TOURIST_ATTRACTIONS_TICKETS_TICKET_PACKAGE"
	MarketingAssetType_TOURIST_ATTRACTIONS_TICKETS_ATTRACTION     MarketingAssetType = "MARKETING_ASSET_TYPE_TOURIST_ATTRACTIONS_TICKETS_ATTRACTION"
	MarketingAssetType_RENOVATION_SERVICES_SERVICE                MarketingAssetType = "MARKETING_ASSET_TYPE_RENOVATION_SERVICES_SERVICE"
	MarketingAssetType_RENOVATION_SERVICES_BRAND                  MarketingAssetType = "MARKETING_ASSET_TYPE_RENOVATION_SERVICES_BRAND"
	MarketingAssetType_FURNITURE_AND_BUILDING_MATERIALS_PRODUCT   MarketingAssetType = "MARKETING_ASSET_TYPE_FURNITURE_AND_BUILDING_MATERIALS_PRODUCT"
	MarketingAssetType_FURNITURE_AND_BUILDING_MATERIALS_BRAND     MarketingAssetType = "MARKETING_ASSET_TYPE_FURNITURE_AND_BUILDING_MATERIALS_BRAND"
	MarketingAssetType_EXHIBITION_SALES_EVENT                     MarketingAssetType = "MARKETING_ASSET_TYPE_EXHIBITION_SALES_EVENT"
	MarketingAssetType_EXHIBITION_SALES_BRAND                     MarketingAssetType = "MARKETING_ASSET_TYPE_EXHIBITION_SALES_BRAND"
)
