/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// LeadsMatchType : 线索匹配类型
type LeadsMatchType string

// List of LeadsMatchType
const (
	LeadsMatchType_NONE         LeadsMatchType = "NONE"
	LeadsMatchType_LEADSID      LeadsMatchType = "LEADSID"
	LeadsMatchType_OUTERLEADSID LeadsMatchType = "OUTERLEADSID"
	LeadsMatchType_CONTACT      LeadsMatchType = "CONTACT"
	LeadsMatchType_CLICKID      LeadsMatchType = "CLICKID"
)
