/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// DeleteStrategy : 组件删除策略
type DeleteStrategy string

// List of DeleteStrategy
const (
	DeleteStrategy_FORCE      DeleteStrategy = "DELETE_STRATEGY_FORCE"
	DeleteStrategy_RESTRICTED DeleteStrategy = "DELETE_STRATEGY_RESTRICTED"
)
