/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 更新单个广告组出价条件
type UpdateBidAmountStruct struct {
	AdgroupId *int64 `json:"adgroup_id,omitempty"`
	BidAmount *int64 `json:"bid_amount,omitempty"`
}
