/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 用户行为数据源结构体
type UserActionSetStruct struct {
	Type_        UserActionSetType `json:"type,omitempty"`
	Id           *int64            `json:"id,omitempty"`
	DataSourceId *int64            `json:"data_source_id,omitempty"`
}
