/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// ConversionTargetType : 数据外显转化目标量类型
type ConversionTargetType string

// List of ConversionTargetType
const (
	ConversionTargetType_DEFAULT    ConversionTargetType = "CONVERSION_TARGET_DEFAULT"
	ConversionTargetType_GET        ConversionTargetType = "CONVERSION_TARGET_GET"
	ConversionTargetType_RESERVE    ConversionTargetType = "CONVERSION_TARGET_RESERVE"
	ConversionTargetType_BOOK       ConversionTargetType = "CONVERSION_TARGET_BOOK"
	ConversionTargetType_BUY        ConversionTargetType = "CONVERSION_TARGET_BUY"
	ConversionTargetType_APPLY      ConversionTargetType = "CONVERSION_TARGET_APPLY"
	ConversionTargetType_CONSULT    ConversionTargetType = "CONVERSION_TARGET_CONSULT"
	ConversionTargetType_DOWNLOAD   ConversionTargetType = "CONVERSION_TARGET_DOWNLOAD"
	ConversionTargetType_PLAYING    ConversionTargetType = "CONVERSION_TARGET_PLAYING"
	ConversionTargetType_CLICK      ConversionTargetType = "CONVERSION_TARGET_CLICK"
	ConversionTargetType_SEE        ConversionTargetType = "CONVERSION_TARGET_SEE"
	ConversionTargetType_INVOLVE    ConversionTargetType = "CONVERSION_TARGET_INVOLVE"
	ConversionTargetType_OPEN       ConversionTargetType = "CONVERSION_TARGET_OPEN"
	ConversionTargetType_PURCHASE   ConversionTargetType = "CONVERSION_TARGET_PURCHASE"
	ConversionTargetType_BROWSE     ConversionTargetType = "CONVERSION_TARGET_BROWSE"
	ConversionTargetType_TRY        ConversionTargetType = "CONVERSION_TARGET_TRY"
	ConversionTargetType_DRIVE      ConversionTargetType = "CONVERSION_TARGET_DRIVE"
	ConversionTargetType_ENTER      ConversionTargetType = "CONVERSION_TARGET_ENTER"
	ConversionTargetType_READ       ConversionTargetType = "CONVERSION_TARGET_READ"
	ConversionTargetType_FOLLOW     ConversionTargetType = "CONVERSION_TARGET_FOLLOW"
	ConversionTargetType_USE        ConversionTargetType = "CONVERSION_TARGET_USE"
	ConversionTargetType_EXPERIENCE ConversionTargetType = "CONVERSION_TARGET_EXPERIENCE"
	ConversionTargetType_SETUP      ConversionTargetType = "CONVERSION_TARGET_SETUP"
	ConversionTargetType_SECKILL    ConversionTargetType = "CONVERSION_TARGET_SECKILL"
	ConversionTargetType_ADD_WECOM  ConversionTargetType = "CONVERSION_TARGET_ADD_WECOM"
	ConversionTargetType_LIKE       ConversionTargetType = "CONVERSION_TARGET_LIKE"
)
