/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 返回结构
type LeadsUpdateListStruct struct {
	Index        *int64  `json:"index,omitempty"`
	OuterLeadsId *string `json:"outer_leads_id,omitempty"`
}
