/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// dsp_tag数据
type RtaExpDspTagDataRecord struct {
	Date                  *int64  `json:"Date,omitempty"`
	DateHour              *int64  `json:"DateHour,omitempty"`
	FUId                  *int64  `json:"FUId,omitempty"`
	DspTag                *int64  `json:"DspTag,omitempty"`
	OuterTargetId         *string `json:"OuterTargetId,omitempty"`
	Cost                  *int64  `json:"Cost,omitempty"`
	ConversionCount       *int64  `json:"ConversionCount,omitempty"`
	SecondConversionCount *int64  `json:"SecondConversionCount,omitempty"`
	ValidExposureCount    *int64  `json:"ValidExposureCount,omitempty"`
	ValidClickCount       *int64  `json:"ValidClickCount,omitempty"`
	MdCheoutFD            *int64  `json:"MdCheoutFD,omitempty"`
	MdCheoutTD            *int64  `json:"MdCheoutTD,omitempty"`
	MdCheoutOW            *int64  `json:"MdCheoutOW,omitempty"`
	MdMgPurchaseVal1      *int64  `json:"MdMgPurchaseVal1,omitempty"`
	MdMgPurchaseVal3      *int64  `json:"MdMgPurchaseVal3,omitempty"`
	MdMgPurchaseVal7      *int64  `json:"MdMgPurchaseVal7,omitempty"`
	MdMgRegUV             *int64  `json:"MdMgRegUV,omitempty"`
}
