/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// ReportGranularity : 异步报表粒度
type ReportGranularity string

// List of ReportGranularity
const (
	ReportGranularity_UNKNOWN ReportGranularity = "UNKNOWN"
	ReportGranularity_HOURLY  ReportGranularity = "HOURLY"
	ReportGranularity_SUMMARY ReportGranularity = "SUMMARY"
	ReportGranularity_DAILY   ReportGranularity = "DAILY"
)
