/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// QualificationType : 资质类型
type QualificationType string

// List of QualificationType
const (
	QualificationType_INDUSTRY_QUALIFICATION            QualificationType = "INDUSTRY_QUALIFICATION"
	QualificationType_AD_QUALIFICATION                  QualificationType = "AD_QUALIFICATION"
	QualificationType_ADDITIONAL_INDUSTRY_QUALIFICATION QualificationType = "ADDITIONAL_INDUSTRY_QUALIFICATION"
)
