/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// PageListQueryType : 落地页状态查询方式
type PageListQueryType string

// List of PageListQueryType
const (
	PageListQueryType_DEFAULT PageListQueryType = "DEFAULT"
	PageListQueryType_DELETED PageListQueryType = "DELETED"
	PageListQueryType_ALL     PageListQueryType = "ALL"
)
