/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// ShootingSceneOutCount : 外景数量
type ShootingSceneOutCount string

// List of ShootingSceneOutCount
const (
	ShootingSceneOutCount_1 ShootingSceneOutCount = "SHOOTING_SCENE_OUT_COUNT_1"
	ShootingSceneOutCount_2 ShootingSceneOutCount = "SHOOTING_SCENE_OUT_COUNT_2"
	ShootingSceneOutCount_3 ShootingSceneOutCount = "SHOOTING_SCENE_OUT_COUNT_3"
	ShootingSceneOutCount_4 ShootingSceneOutCount = "SHOOTING_SCENE_OUT_COUNT_4"
	ShootingSceneOutCount_5 ShootingSceneOutCount = "SHOOTING_SCENE_OUT_COUNT_5"
	ShootingSceneOutCount_6 ShootingSceneOutCount = "SHOOTING_SCENE_OUT_COUNT_6"
	ShootingSceneOutCount_7 ShootingSceneOutCount = "SHOOTING_SCENE_OUT_COUNT_7"
	ShootingSceneOutCount_N ShootingSceneOutCount = "SHOOTING_SCENE_OUT_COUNT_N"
)
