/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 橱窗图片结构
type ImageShowcaseStruct struct {
	Image     *ImageStruct     `json:"image,omitempty"`
	ImageList *ImageListStruct `json:"image_list,omitempty"`
}
