/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// SmartTargetingStatus : 广告智能定向状态
type SmartTargetingStatus string

// List of SmartTargetingStatus
const (
	SmartTargetingStatus_NONE SmartTargetingStatus = "SMART_TARGETING_NONE"
	SmartTargetingStatus_AUTO SmartTargetingStatus = "SMART_TARGETING_AUTO"
)
