/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// ConfiguredStatus : 客户设置的状态
type ConfiguredStatus string

// List of ConfiguredStatus
const (
	ConfiguredStatus_NORMAL  ConfiguredStatus = "AD_STATUS_NORMAL"
	ConfiguredStatus_SUSPEND ConfiguredStatus = "AD_STATUS_SUSPEND"
)
