/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 橱窗图片组件
type ImageShowcaseComponent struct {
	ComponentId *int64               `json:"component_id,omitempty"`
	Value       *ImageShowcaseStruct `json:"value,omitempty"`
}
