/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type ProductSeriesAddResponseData struct {
	ProductSeriesId   *int64  `json:"product_series_id,omitempty"`
	ProductSeriesName *string `json:"product_series_name,omitempty"`
}
