/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type AdvertiserUpdateRequest struct {
	AccountId               *int64                   `json:"account_id,omitempty"`
	DailyBudget             *int64                   `json:"daily_budget,omitempty"`
	CorporationName         *string                  `json:"corporation_name,omitempty"`
	CorporationLicence      *string                  `json:"corporation_licence,omitempty"`
	CertificationImageId    *string                  `json:"certification_image_id,omitempty"`
	IndividualQualification *IndividualQualification `json:"individual_qualification,omitempty"`
	AreaCode                *int64                   `json:"area_code,omitempty"`
	SystemIndustryId        *int64                   `json:"system_industry_id,omitempty"`
	IntroductionUrl         *string                  `json:"introduction_url,omitempty"`
	CorporateBrandName      *string                  `json:"corporate_brand_name,omitempty"`
	ContactPersonTelephone  *string                  `json:"contact_person_telephone,omitempty"`
	ContactPersonMobile     *string                  `json:"contact_person_mobile,omitempty"`
	BusinessAlias           *string                  `json:"business_alias,omitempty"`
	Websites                *[]WebsiteUpdateStruct   `json:"websites,omitempty"`
}
