/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 渠道号信息
type CreateSplitChannelStruct struct {
	ChannelId           *string `json:"channel_id,omitempty"`
	ChannelName         *string `json:"channel_name,omitempty"`
	CustomizedChannelId *string `json:"customized_channel_id,omitempty"`
}
