/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 衍生创意自定义模版信息
type DeriveTemplateConf struct {
	TemplateConfList *[]TemplateConfItem `json:"template_conf_list,omitempty"`
}
