/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 激励浏览组件
type RewardedBrowseComponent struct {
	ComponentId *int64                `json:"component_id,omitempty"`
	Value       *RewardedBrowseStruct `json:"value,omitempty"`
	IsDeleted   *bool                 `json:"is_deleted,omitempty"`
}
