/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// AdvertiserTypeEnum : 广告主类型
type AdvertiserTypeEnum string

// List of AdvertiserTypeEnum
const (
	AdvertiserTypeEnum_DIRECT_ADVERTISER AdvertiserTypeEnum = "DIRECT_ADVERTISER"
	AdvertiserTypeEnum_SUB_ADVERTISER    AdvertiserTypeEnum = "SUB_ADVERTISER"
)
