/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 文本组件元素
type ElementText struct {
	Text *string `json:"text,omitempty"`
}
