/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 返回结构
type WechatStoreCatalogsGetListStruct struct {
	CatalogId        *int64    `json:"catalog_id,omitempty"`
	CatalogName      *string   `json:"catalog_name,omitempty"`
	StoreId          *string   `json:"store_id,omitempty"`
	AvailableStatus  *int64    `json:"available_status,omitempty"`
	UnavailableCause *[]string `json:"unavailable_cause,omitempty"`
}
