/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type RtatargetDeleteRequest struct {
	Data *[]RtaTargetDeleteObject `json:"data,omitempty"`
}
