/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 视频号信息组件
type WechatChannelsStruct struct {
	LivePromotedType       LivePromotedType `json:"live_promoted_type,omitempty"`
	Username               *string          `json:"username,omitempty"`
	FinderObjectVisibility *bool            `json:"finder_object_visibility,omitempty"`
}
