/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// MuseAiDimensionSize : 妙思AI素材尺寸
type MuseAiDimensionSize string

// List of MuseAiDimensionSize
const (
	MuseAiDimensionSize_1280720 MuseAiDimensionSize = "SIZE_1280_720"
	MuseAiDimensionSize_7201280 MuseAiDimensionSize = "SIZE_720_1280"
	MuseAiDimensionSize_800800  MuseAiDimensionSize = "SIZE_800_800"
)
