/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 应用下载Android元素
type CanvasAppAndroidSpecType struct {
	AppAndroidId               *string `json:"app_android_id,omitempty"`
	DeepLinkUrl                *string `json:"deep_link_url,omitempty"`
	AppAndroidChannelPackageId *string `json:"app_android_channel_package_id,omitempty"`
	AppMarketPackage           *string `json:"app_market_package,omitempty"`
}
