/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type QualificationsAddRequest struct {
	AccountId         *int64             `json:"account_id,omitempty"`
	QualificationType QualificationType  `json:"qualification_type,omitempty"`
	QualificationSpec *QualificationSpec `json:"qualification_spec,omitempty"`
}
