/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 官方落地页结构数据
type OfficialPageStruct struct {
	PageId        *int64             `json:"page_id,omitempty"`
	LandingPageId *int64             `json:"landing_page_id,omitempty"`
	PageName      *string            `json:"page_name,omitempty"`
	PageTitle     *string            `json:"page_title,omitempty"`
	PageType      OfficialPageType   `json:"page_type,omitempty"`
	PageStatus    OfficialPageStatus `json:"page_status,omitempty"`
}
