/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type WechatChannelsAuthorizationUpdateResponseData struct {
	AuthorizationId *string `json:"authorization_id,omitempty"`
}
