/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 简单文本组件配置
type BlockTextConfig struct {
	Content      *string `json:"content,omitempty"`
	Color        *string `json:"color,omitempty"`
	FontSize     *string `json:"font_size,omitempty"`
	FontWeight   *string `json:"font_weight,omitempty"`
	FontStyle    *string `json:"font_style,omitempty"`
	TextAlign    *string `json:"text_align,omitempty"`
	MarginTop    *int64  `json:"margin_top,omitempty"`
	MarginBottom *int64  `json:"margin_bottom,omitempty"`
}
