/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// OauthAccountRoleType : 授权账号身份类型
type OauthAccountRoleType string

// List of OauthAccountRoleType
const (
	OauthAccountRoleType_ADVERTISER       OauthAccountRoleType = "ACCOUNT_ROLE_TYPE_ADVERTISER"
	OauthAccountRoleType_AGENCY           OauthAccountRoleType = "ACCOUNT_ROLE_TYPE_AGENCY"
	OauthAccountRoleType_T1               OauthAccountRoleType = "ACCOUNT_ROLE_TYPE_T1"
	OauthAccountRoleType_BUSINESS_MANAGER OauthAccountRoleType = "ACCOUNT_ROLE_TYPE_BUSINESS_MANAGER"
	OauthAccountRoleType_DATA_NEXUS       OauthAccountRoleType = "ACCOUNT_ROLE_TYPE_DATA_NEXUS"
)
