/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// CategoryType : 行为兴趣意向定向标签类型
type CategoryType string

// List of CategoryType
const (
	CategoryType_INTEREST  CategoryType = "INTEREST"
	CategoryType_BEHAVIOR  CategoryType = "BEHAVIOR"
	CategoryType_INTENTION CategoryType = "INTENTION"
)
