/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 直播实时画面组件
type ChannelsLiveFeedStruct struct {
	WechatChannelsAccountId *string `json:"wechat_channels_account_id,omitempty"`
	RewardedMaskSwitch      *bool   `json:"rewarded_mask_switch,omitempty"`
}
