/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// EndPageType : 结束页类型
type EndPageType string

// List of EndPageType
const (
	EndPageType_AVATAR_NICKNAME_HIGHLIGHT EndPageType = "END_PAGE_AVATAR_NICKNAME_HIGHLIGHT"
	EndPageType_DESCRIPTION_HIGHLIGHT     EndPageType = "END_PAGE_DESCRIPTION_HIGHLIGHT"
)
