/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// PageStatus : 状态
type PageStatus string

// List of PageStatus
const (
	PageStatus_NORMAL  PageStatus = "NORMAL"
	PageStatus_DELETED PageStatus = "DELETED"
	PageStatus_PENDING PageStatus = "PENDING"
)
