/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 小店智投-净成交ROI
type SmartDeliveryGoalWechatStoreNetProfitRoiSpec struct {
	DeepConversionWorthRate *float64 `json:"deep_conversion_worth_rate,omitempty"`
}
