/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 落地页准入控制
type LandingPageAccess struct {
	SupportPageTypes *[]string `json:"support_page_types,omitempty"`
	MustNotPageTypes *[]string `json:"must_not_page_types,omitempty"`
	MustPageTypes    *[]string `json:"must_page_types,omitempty"`
}
