/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// RTA实验信息
type RtaExpListRecord struct {
	ExpId    *int64   `json:"ExpId,omitempty"`
	ExpName  *string  `json:"ExpName,omitempty"`
	FlowRate *int64   `json:"FlowRate,omitempty"`
	EndTime  *string  `json:"EndTime,omitempty"`
	SiteSet  *[]int64 `json:"SiteSet,omitempty"`
	Status   *int64   `json:"Status,omitempty"`
}
