/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 素材信息
type EachMaterialItemStruct struct {
	MaterialId *string `json:"material_id,omitempty"`
}
