/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 返回结构
type WalletBindingAccountStruct struct {
	Uid                   *int64                     `json:"uid,omitempty"`
	Uname                 *string                    `json:"uname,omitempty"`
	AdvertiserStatus      *string                    `json:"advertiser_status,omitempty"`
	BindStatus            *string                    `json:"bind_status,omitempty"`
	BindTime              *int64                     `json:"bind_time,omitempty"`
	CreateTime            *int64                     `json:"create_time,omitempty"`
	YesterdayCost         *int64                     `json:"yesterday_cost,omitempty"`
	TotalBalance          *int64                     `json:"total_balance,omitempty"`
	TodayCost             *int64                     `json:"today_cost,omitempty"`
	Kframe                *string                    `json:"kframe,omitempty"`
	BalanceInfoList       *[]WalletListBalanceStruct `json:"balance_info_list,omitempty"`
	IndustryId            *string                    `json:"industry_id,omitempty"`
	IndustryName          *string                    `json:"industry_name,omitempty"`
	AdvertiserDailyBudget *int64                     `json:"advertiser_daily_budget,omitempty"`
	IdentityCheck         *bool                      `json:"identity_check,omitempty"`
	DepositCheck          *bool                      `json:"deposit_check,omitempty"`
}
