/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type SaasMiniprogramPrereviewAddRequest struct {
	AccountId                       *int64                 `json:"account_id,omitempty"`
	MiniProgramId                   *string                `json:"mini_program_id,omitempty"`
	ProductId                       *string                `json:"product_id,omitempty"`
	MiniProgramPath                 *string                `json:"mini_program_path,omitempty"`
	ProductDetailPageSignature      *string                `json:"product_detail_page_signature,omitempty"`
	SaasMiniprogramPreviewQrcodeUrl *string                `json:"saas_miniprogram_preview_qrcode_url,omitempty"`
	ComponentInfo                   *[]SaasComponentStruct `json:"component_info,omitempty"`
}
