/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type ChannelsLivenoticeinfoGetResponseData struct {
	LiveNoticeRecordList *[]LiveNoticeRecord `json:"live_notice_record_list,omitempty"`
}
