/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 分页内容
type PunishPageConf struct {
	Page      *int64 `json:"page,omitempty"`
	PageSize  *int64 `json:"page_size,omitempty"`
	TotalPage *int64 `json:"total_page,omitempty"`
	TotalNum  *int64 `json:"total_num,omitempty"`
}
