/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 更新单个广告组投放时间条件
type UpdateDatetimeStruct struct {
	AdgroupId  *int64  `json:"adgroup_id,omitempty"`
	BeginDate  *string `json:"begin_date,omitempty"`
	EndDate    *string `json:"end_date,omitempty"`
	TimeSeries *string `json:"time_series,omitempty"`
}
