/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// XjPageType : 蹊径落地页类型
type XjPageType string

// List of XJPageType
const (
	XjPageType_DEFAULT_H5         XjPageType = "XJ_DEFAULT_H5"
	XjPageType_ANDROID_APP_H5     XjPageType = "XJ_ANDROID_APP_H5"
	XjPageType_IOS_APP_H5         XjPageType = "XJ_IOS_APP_H5"
	XjPageType_WEBSITE_H5         XjPageType = "XJ_WEBSITE_H5"
	XjPageType_ANDROID_APP_NATIVE XjPageType = "XJ_ANDROID_APP_NATIVE"
	XjPageType_IOS_APP_NATIVE     XjPageType = "XJ_IOS_APP_NATIVE"
	XjPageType_WEBSITE_NATIVE     XjPageType = "XJ_WEBSITE_NATIVE"
	XjPageType_FENGLING_LBS       XjPageType = "XJ_FENGLING_LBS"
)
