/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 微信客服元素
type WechatServiceSpec struct {
	WechatServiceUrl *string `json:"wechat_service_url,omitempty"`
}
