/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 顶部文本组件配置
type HeadTextConfig struct {
	Title  *CompHeadTextStruct `json:"title,omitempty"`
	Detail *CompHeadTextStruct `json:"detail,omitempty"`
}
