/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// PageSource : 查询类型
type PageSource string

// List of PageSource
const (
	PageSource_GRANT PageSource = "GRANT"
	PageSource_OWNER PageSource = "OWNER"
)
