/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type QualificationImagesAddResponseData struct {
	ImageId  *string `json:"image_id,omitempty"`
	ImageUrl *string `json:"image_url,omitempty"`
}
