/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// WechatShopCardType : 小店商品卡类型
type WechatShopCardType string

// List of WechatShopCardType
const (
	WechatShopCardType_NORMAL     WechatShopCardType = "WECHAT_SHOP_CARD_TYPE_NORMAL"
	WechatShopCardType_SHOP_VISIT WechatShopCardType = "WECHAT_SHOP_CARD_TYPE_SHOP_VISIT"
)
