/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 返回结构
type SubsidyAccountBindAddListStruct struct {
	AccountId      *int64  `json:"account_id,omitempty"`
	BoundAccountId *int64  `json:"bound_account_id,omitempty"`
	BindStatus     *string `json:"bind_status,omitempty"`
}
