/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type WecomCustomerAcquisitionLinkAddRequest struct {
	AccountId        *int64    `json:"account_id,omitempty"`
	CorpId           *string   `json:"corp_id,omitempty"`
	LinkName         *string   `json:"link_name,omitempty"`
	UserIdList       *[]string `json:"user_id_list,omitempty"`
	DepartmentIdList *[]int64  `json:"department_id_list,omitempty"`
	SkipVerify       *bool     `json:"skip_verify,omitempty"`
}
