/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type CustomAudienceFilesAddResponseData struct {
	CustomAudienceFileId *int64 `json:"custom_audience_file_id,omitempty"`
}
