/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type EcommerceOrderUpdateRequest struct {
	AccountId              *int64         `json:"account_id,omitempty"`
	EcommerceOrderId       *string        `json:"ecommerce_order_id,omitempty"`
	DeliveryTrackingNumber *string        `json:"delivery_tracking_number,omitempty"`
	ExpressCompany         ExpressCompany `json:"express_company,omitempty"`
}
