/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// FileType : 文件类型
type FileType string

// List of FileType
const (
	FileType_PDF FileType = "PDF"
	FileType_DOC FileType = "DOC"
)
