/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// OperateSuggestion : 操作建议
type OperateSuggestion string

// List of OperateSuggestion
const (
	OperateSuggestion_OBSERVATION OperateSuggestion = "OPERATE_SUGGESTION_OBSERVATION"
	OperateSuggestion_OPERATION   OperateSuggestion = "OPERATE_SUGGESTION_OPERATION"
	OperateSuggestion_PAUSE       OperateSuggestion = "OPERATE_SUGGESTION_PAUSE"
	OperateSuggestion_FINE_PLAY   OperateSuggestion = "OPERATE_SUGGESTION_FINE_PLAY"
	OperateSuggestion_SUSPEND     OperateSuggestion = "OPERATE_SUGGESTION_SUSPEND"
	OperateSuggestion_TRAFFIC     OperateSuggestion = "OPERATE_SUGGESTION_TRAFFIC"
	OperateSuggestion_KEEP        OperateSuggestion = "OPERATE_SUGGESTION_KEEP"
)
