/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type CustomAudiencesUpdateRequest struct {
	AccountId   *int64  `json:"account_id,omitempty"`
	AudienceId  *int64  `json:"audience_id,omitempty"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Cooperated  *bool   `json:"cooperated,omitempty"`
}
