/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// MarketingSubGoal : 二级营销目的类型
type MarketingSubGoal string

// List of MarketingSubGoal
const (
	MarketingSubGoal_UNKNOWN                              MarketingSubGoal = "MARKETING_SUB_GOAL_UNKNOWN"
	MarketingSubGoal_NEW_GAME_RESERVE                     MarketingSubGoal = "MARKETING_SUB_GOAL_NEW_GAME_RESERVE"
	MarketingSubGoal_NEW_GAME_TEST                        MarketingSubGoal = "MARKETING_SUB_GOAL_NEW_GAME_TEST"
	MarketingSubGoal_NEW_GAME_LAUNCH                      MarketingSubGoal = "MARKETING_SUB_GOAL_NEW_GAME_LAUNCH"
	MarketingSubGoal_PLATEAU_PHASE_LAUNCH                 MarketingSubGoal = "MARKETING_SUB_GOAL_PLATEAU_PHASE_LAUNCH"
	MarketingSubGoal_MINI_GAME_NEW_CUSTOMER_GROWTH        MarketingSubGoal = "MARKETING_SUB_GOAL_MINI_GAME_NEW_CUSTOMER_GROWTH"
	MarketingSubGoal_MINI_GAME_RETURN_CUSTOMER_ENGAGEMENT MarketingSubGoal = "MARKETING_SUB_GOAL_MINI_GAME_RETURN_CUSTOMER_ENGAGEMENT"
	MarketingSubGoal_APP_ACQUISITION                      MarketingSubGoal = "MARKETING_SUB_GOAL_APP_ACQUISITION"
	MarketingSubGoal_APP_ACTIVATION                       MarketingSubGoal = "MARKETING_SUB_GOAL_APP_ACTIVATION"
	MarketingSubGoal_NOT_INSTALL_USER                     MarketingSubGoal = "MARKETING_SUB_GOAL_NOT_INSTALL_USER"
	MarketingSubGoal_PRE_INSTALL_USER                     MarketingSubGoal = "MARKETING_SUB_GOAL_PRE_INSTALL_USER"
	MarketingSubGoal_UNLOADED_USER                        MarketingSubGoal = "MARKETING_SUB_GOAL_UNLOADED_USER"
	MarketingSubGoal_SHORT_INACTIVE_USER                  MarketingSubGoal = "MARKETING_SUB_GOAL_SHORT_INACTIVE_USER"
	MarketingSubGoal_LONG_INACTIVE_USER                   MarketingSubGoal = "MARKETING_SUB_GOAL_LONG_INACTIVE_USER"
	MarketingSubGoal_GAME_VERSION_UPGRADE                 MarketingSubGoal = "MARKETING_SUB_GOAL_GAME_VERSION_UPGRADE"
)
