/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type WechatShopAuthorizationStatusUpdateRequest struct {
	AccountId           *int64                   `json:"account_id,omitempty"`
	AuthorizationId     *int64                   `json:"authorization_id,omitempty"`
	AuthorizationStatus WechatChannelsAuthStatus `json:"authorization_status,omitempty"`
}
