/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 微信号信息数据结构
type PackageInfoStruct struct {
	PackageId   *int64            `json:"package_id,omitempty"`
	PackageType WechatPackageType `json:"package_type,omitempty"`
	PackageName *string           `json:"package_name,omitempty"`
	WechatIds   *string           `json:"wechat_ids,omitempty"`
	IsDeleted   *int64            `json:"is_deleted,omitempty"`
	UpdateTime  *string           `json:"update_time,omitempty"`
	CreateTime  *string           `json:"create_time,omitempty"`
}
