/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// BusinessPrice : 商务服务价格
type BusinessPrice string

// List of BusinessPrice
const (
	BusinessPrice_FREE        BusinessPrice = "BUSINESS_PRICE_FREE"
	BusinessPrice_1TO50       BusinessPrice = "BUSINESS_PRICE_1_TO_50"
	BusinessPrice_51TO100     BusinessPrice = "BUSINESS_PRICE_51_TO_100"
	BusinessPrice_101TO200    BusinessPrice = "BUSINESS_PRICE_101_TO_200"
	BusinessPrice_201TO1000   BusinessPrice = "BUSINESS_PRICE_201_TO_1000"
	BusinessPrice_1001TO3000  BusinessPrice = "BUSINESS_PRICE_1001_TO_3000"
	BusinessPrice_3001TO5000  BusinessPrice = "BUSINESS_PRICE_3001_TO_5000"
	BusinessPrice_5001TO8000  BusinessPrice = "BUSINESS_PRICE_5001_TO_8000"
	BusinessPrice_8001TO12000 BusinessPrice = "BUSINESS_PRICE_8001_TO_12000"
	BusinessPrice_OUT_12000   BusinessPrice = "BUSINESS_PRICE_OUT_12000"
)
