/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// ProductSetSpecFieldValueOperator : 商品系列字段值操作符
type ProductSetSpecFieldValueOperator string

// List of ProductSetSpecFieldValueOperator
const (
	ProductSetSpecFieldValueOperator_EQUALS         ProductSetSpecFieldValueOperator = "EQUALS"
	ProductSetSpecFieldValueOperator_IN             ProductSetSpecFieldValueOperator = "IN"
	ProductSetSpecFieldValueOperator_LESS_EQUALS    ProductSetSpecFieldValueOperator = "LESS_EQUALS"
	ProductSetSpecFieldValueOperator_LESS           ProductSetSpecFieldValueOperator = "LESS"
	ProductSetSpecFieldValueOperator_GREATER_EQUALS ProductSetSpecFieldValueOperator = "GREATER_EQUALS"
	ProductSetSpecFieldValueOperator_GREATER        ProductSetSpecFieldValueOperator = "GREATER"
	ProductSetSpecFieldValueOperator_RANGE          ProductSetSpecFieldValueOperator = "RANGE"
)
