/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// DpaApiCatalogType : 商品库类型
type DpaApiCatalogType string

// List of DpaApiCatalogType
const (
	DpaApiCatalogType_UNKNOWN     DpaApiCatalogType = "CATALOG_TYPE_UNKNOWN"
	DpaApiCatalogType_STANDARD    DpaApiCatalogType = "CATALOG_TYPE_STANDARD"
	DpaApiCatalogType_FENGYE      DpaApiCatalogType = "CATALOG_TYPE_FENGYE"
	DpaApiCatalogType_LOCAL_STORE DpaApiCatalogType = "CATALOG_TYPE_LOCAL_STORE"
)
