/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// MarketingCarrierType : 营销载体类型
type MarketingCarrierType string

// List of MarketingCarrierType
const (
	MarketingCarrierType_UNKNOWN                          MarketingCarrierType = "MARKETING_CARRIER_TYPE_UNKNOWN"
	MarketingCarrierType_APP_ANDROID                      MarketingCarrierType = "MARKETING_CARRIER_TYPE_APP_ANDROID"
	MarketingCarrierType_APP_IOS                          MarketingCarrierType = "MARKETING_CARRIER_TYPE_APP_IOS"
	MarketingCarrierType_WECHAT_OFFICIAL_ACCOUNT          MarketingCarrierType = "MARKETING_CARRIER_TYPE_WECHAT_OFFICIAL_ACCOUNT"
	MarketingCarrierType_JUMP_PAGE                        MarketingCarrierType = "MARKETING_CARRIER_TYPE_JUMP_PAGE"
	MarketingCarrierType_WECHAT_MINI_GAME                 MarketingCarrierType = "MARKETING_CARRIER_TYPE_WECHAT_MINI_GAME"
	MarketingCarrierType_WECHAT_CHANNELS_LIVE             MarketingCarrierType = "MARKETING_CARRIER_TYPE_WECHAT_CHANNELS_LIVE"
	MarketingCarrierType_WECHAT_CHANNELS                  MarketingCarrierType = "MARKETING_CARRIER_TYPE_WECHAT_CHANNELS"
	MarketingCarrierType_WECHAT_CHANNELS_LIVE_RESERVATION MarketingCarrierType = "MARKETING_CARRIER_TYPE_WECHAT_CHANNELS_LIVE_RESERVATION"
	MarketingCarrierType_MINI_PROGRAM_WECHAT              MarketingCarrierType = "MARKETING_CARRIER_TYPE_MINI_PROGRAM_WECHAT"
	MarketingCarrierType_APP_QUICK_APP                    MarketingCarrierType = "MARKETING_CARRIER_TYPE_APP_QUICK_APP"
	MarketingCarrierType_JUMP_PAGE2                       MarketingCarrierType = "MARKETING_CARRIER_TYPE_JUMP_PAGE2"
	MarketingCarrierType_MINI_PROGRAM_WECHAT2             MarketingCarrierType = "MARKETING_CARRIER_TYPE_MINI_PROGRAM_WECHAT2"
	MarketingCarrierType_PC_GAME                          MarketingCarrierType = "MARKETING_CARRIER_TYPE_PC_GAME"
	MarketingCarrierType_QQ_MINI_GAME                     MarketingCarrierType = "MARKETING_CARRIER_TYPE_QQ_MINI_GAME"
)
