/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// oCPA深度优化内容
type DeepConversionSpec struct {
	DeepConversionType                 DeepConversionType                  `json:"deep_conversion_type,omitempty"`
	DeepConversionBehaviorSpec         *DeepConversionBehaviorSpec         `json:"deep_conversion_behavior_spec,omitempty"`
	DeepConversionWorthSpec            *DeepConversionWorthSpec            `json:"deep_conversion_worth_spec,omitempty"`
	DeepConversionWorthAdvancedSpec    *DeepConversionWorthAdvancedSpec    `json:"deep_conversion_worth_advanced_spec,omitempty"`
	DeepConversionBehaviorAdvancedSpec *DeepConversionBehaviorAdvancedSpec `json:"deep_conversion_behavior_advanced_spec,omitempty"`
}
