/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 返回结构
type TargetingsGetListStruct struct {
	TargetingName        *string               `json:"targeting_name,omitempty"`
	Targeting            *ReadTargetingSetting `json:"targeting,omitempty"`
	TargetingTranslation *string               `json:"targeting_translation,omitempty"`
	IsDeleted            *bool                 `json:"is_deleted,omitempty"`
	CreatedTime          *int64                `json:"created_time,omitempty"`
	LastModifiedTime     *int64                `json:"last_modified_time,omitempty"`
	TargetingSourceType  TargetingSourceType   `json:"targeting_source_type,omitempty"`
	ShareFromAccountId   *int64                `json:"share_from_account_id,omitempty"`
	ShareFromTargetingId *int64                `json:"share_from_targeting_id,omitempty"`
	TargetingId          *int64                `json:"targeting_id,omitempty"`
	TargetingSourceMsg   *string               `json:"targeting_source_msg,omitempty"`
}
