/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type LeadsCallRecordsGetResponseData struct {
	PageInfo  *LeadsWebPageInfoStruct `json:"page_info,omitempty"`
	RequestId *string                 `json:"request_id,omitempty"`
	Entities  *[]CallListStruct       `json:"entities,omitempty"`
}
