/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type WalletBasicInfoGetResponseData struct {
	WalletInfo *WalletBasicInfoGetWalletInfo `json:"wallet_info,omitempty"`
}
