/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// MultiImageCollageAigcStatus : 多图智拼AIGC开关状态
type MultiImageCollageAigcStatus string

// List of MultiImageCollageAigcStatus
const (
	MultiImageCollageAigcStatus_UNKNOWN MultiImageCollageAigcStatus = "MULTI_IMAGE_COLLAGE_AIGC_STATUS_UNKNOWN"
	MultiImageCollageAigcStatus_DISABLE MultiImageCollageAigcStatus = "MULTI_IMAGE_COLLAGE_AIGC_STATUS_DISABLE"
	MultiImageCollageAigcStatus_ENABLE  MultiImageCollageAigcStatus = "MULTI_IMAGE_COLLAGE_AIGC_STATUS_ENABLE"
)
