/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type WechatChannelsAdAccountWechatBindingGetResponseData struct {
	WechatBindStatus WechatChannelsAdAccountBindWechatStatus `json:"wechat_bind_status,omitempty"`
	AuthorNickName   *string                                 `json:"author_nick_name,omitempty"`
}
