/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 文案信息结构
type TextListStruct struct {
	Text *string `json:"text,omitempty"`
	Tag  *string `json:"tag,omitempty"`
}
