/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type WechatChannelsAdAccountUpdateResponseData struct {
	WechatChannelsAdAccountId *int64 `json:"wechat_channels_ad_account_id,omitempty"`
}
