/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type AdgroupsUpdateDailyBudgetResponseData struct {
	List       *[]AdgroupsUpdateDailyBudgetListStruct `json:"list,omitempty"`
	FailIdList *[]int64                               `json:"fail_id_list,omitempty"`
}
