/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// ConversionLinkFirstCategoryType : 营销链路一级分类
type ConversionLinkFirstCategoryType string

// List of ConversionLinkFirstCategoryType
const (
	ConversionLinkFirstCategoryType_WECHAT    ConversionLinkFirstCategoryType = "WECHAT"
	ConversionLinkFirstCategoryType_MINI_GAME ConversionLinkFirstCategoryType = "MINI_GAME"
	ConversionLinkFirstCategoryType_QUICK_APP ConversionLinkFirstCategoryType = "QUICK_APP"
	ConversionLinkFirstCategoryType_WEB       ConversionLinkFirstCategoryType = "WEB"
)
