/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 组件list内容联合校验长度
type ComponentMetadataValueValidEnumOption struct {
	Value        *string `json:"value,omitempty"`
	Desc         *string `json:"desc,omitempty"`
	Support3link *bool   `json:"support_3link,omitempty"`
	Required     *bool   `json:"required,omitempty"`
}
