/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// DeriveDataVersion : 衍生数据版本
type DeriveDataVersion string

// List of DeriveDataVersion
const (
	DeriveDataVersion_V1 DeriveDataVersion = "DERIVE_DATA_VERSION_V1"
	DeriveDataVersion_V3 DeriveDataVersion = "DERIVE_DATA_VERSION_V3"
)
