/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 创建应用宝渠道包接口任务所需条件
type CreateAndroidChannelPackageSpec struct {
	PackageName *string `json:"package_name,omitempty"`
	DownloadUrl *string `json:"download_url,omitempty"`
}
