/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type CommentListGetResponseData struct {
	List         *[]CommentListGetListStruct `json:"list,omitempty"`
	LastBuffer   *string                     `json:"last_buffer,omitempty"`
	ContinueFlag *int64                      `json:"continue_flag,omitempty"`
}
