/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type ProductSeriesAddRequest struct {
	AccountId  *int64             `json:"account_id,omitempty"`
	CatalogId  *int64             `json:"catalog_id,omitempty"`
	SeriesName *string            `json:"series_name,omitempty"`
	Definition *ProductSeriesSpec `json:"definition,omitempty"`
}
