/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type MuseAiTaskAddRequest struct {
	AccountId      *int64             `json:"account_id,omitempty"`
	TaskType       MuseAiTaskType     `json:"task_type,omitempty"`
	OutputImageNum *int64             `json:"output_image_num,omitempty"`
	Img2img        *Img2imgStruct     `json:"img2img,omitempty"`
	Text2img       *Text2imgStruct    `json:"text2img,omitempty"`
	Img2caption    *Img2captionStruct `json:"img2caption,omitempty"`
}
