/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 视频素材属性信息
type MediaInfoItem struct {
	Name  *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`
}
