/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type WalletTransferAddRequest struct {
	AccountId       *int64         `json:"account_id,omitempty"`
	ToAccountId     *int64         `json:"to_account_id,omitempty"`
	FundType        AccountTypeMap `json:"fund_type,omitempty"`
	Amount          *int64         `json:"amount,omitempty"`
	TransferType    *string        `json:"transfer_type,omitempty"`
	TransferTryBest *int64         `json:"transfer_try_best,omitempty"`
	ExternalBillNo  *string        `json:"external_bill_no,omitempty"`
	Memo            *string        `json:"memo,omitempty"`
}
