/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 基础图片组件元素
type ImageSpec struct {
	ImageIdList   *string `json:"image_id_list,omitempty"`
	Width         *int64  `json:"width,omitempty"`
	Height        *int64  `json:"height,omitempty"`
	PaddingTop    *int64  `json:"padding_top,omitempty"`
	PaddingBottom *int64  `json:"padding_bottom,omitempty"`
}
