/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 删除广告创意
type DeleteDynamicCreativeItem struct {
	DynamicCreativeId *int64 `json:"dynamic_creative_id,omitempty"`
}
