/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 返回结构
type DeepWorthAdvancedGoalPermissionStruct struct {
	OptimizationGoal          OptimizationGoal `json:"optimization_goal,omitempty"`
	DeepWorthAdvancedGoalList *[]string        `json:"deep_worth_advanced_goal_list,omitempty"`
}
