/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 微信公众号详情数据
type WechatOfficialAccountDetailPageSpec struct {
	AppId *string `json:"app_id,omitempty"`
}
