/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 小程序信息
type MiniProgramSpec struct {
	Title            *string   `json:"title,omitempty"`
	MiniProgramId    *string   `json:"mini_program_id,omitempty"`
	MiniProgramPath  *string   `json:"mini_program_path,omitempty"`
	MiniProgramPaths *[]string `json:"mini_program_paths,omitempty"`
}
