/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 资质文件
type AdAccountCertificationFile struct {
	CertificationFileId   *string `json:"certification_file_id,omitempty"`
	CertificationFileName *string `json:"certification_file_name,omitempty"`
	CertificationFile     *string `json:"certification_file,omitempty"`
}
