/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 素材信息
type MaterialGroupStruct struct {
	MaterialGroupId           *int64                     `json:"material_group_id,omitempty"`
	Ratio                     *string                    `json:"ratio,omitempty"`
	MaterialType              TemplateType               `json:"material_type,omitempty"`
	Materials                 *[]MaterialStruct          `json:"materials,omitempty"`
	OriginalCreativeTemplates *[]DimensionStruct         `json:"original_creative_templates,omitempty"`
	TargetCreativeTemplates   *[]DimensionStruct         `json:"target_creative_templates,omitempty"`
	Previews                  *[]PreviewStruct           `json:"previews,omitempty"`
	RecommendTemplates        *[]RecommendTemplateStruct `json:"recommend_templates,omitempty"`
}
