/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 门店营业时间信息结构
type OpeningHours struct {
	TimeSeries *string                  `json:"time_series,omitempty"`
	Date       LocalStorePeakPeriodDate `json:"date,omitempty"`
}
