/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 橱窗视频结构
type VideoShowcaseStruct struct {
	Video     *VideoStruct     `json:"video,omitempty"`
	ImageList *ImageListStruct `json:"image_list,omitempty"`
}
