/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type MuseAiTaskGetResponseData struct {
	TaskId     *int64              `json:"task_id,omitempty"`
	TaskType   MuseAiTaskType      `json:"task_type,omitempty"`
	TaskStatus MuseAiTaskStatus    `json:"task_status,omitempty"`
	Results    *[]MuseAiResultItem `json:"results,omitempty"`
}
