/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// BillingModel : 智投出价结算模式
type BillingModel string

// List of BillingModel
const (
	BillingModel_UNKNOWN BillingModel = "BILLING_MODEL_UNKNOWN"
	BillingModel_CPA     BillingModel = "BILLING_MODEL_CPA"
)
