/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 视频号活动页落地页信息
type WechatChannelsActivitySpec struct {
	ActivityId              *string `json:"activity_id,omitempty"`
	WechatChannelsAccountId *string `json:"wechat_channels_account_id,omitempty"`
	ActivityName            *string `json:"activity_name,omitempty"`
}
