/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 顶部视频组件配置
type HeadVideoConfig struct {
	MaterialId *string `json:"material_id,omitempty"`
}
