/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 预览数据信息
type PreviewUpdateStruct struct {
	MaterialDerivePreviewId *int64 `json:"material_derive_preview_id,omitempty"`
	TemplateId              *int64 `json:"template_id,omitempty"`
	CreativeTemplateId      *int64 `json:"creative_template_id,omitempty"`
}
