/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 返回结构
type ConversionLinkAssetsGetListStruct struct {
	ConversionLinkAssetId *int64                           `json:"conversion_link_asset_id,omitempty"`
	Version               *int64                           `json:"version,omitempty"`
	Name                  *string                          `json:"name,omitempty"`
	MarketingCarrierName  *string                          `json:"marketing_carrier_name,omitempty"`
	MarketingCarrierId    *string                          `json:"marketing_carrier_id,omitempty"`
	FirstCategoryType     ConversionLinkFirstCategoryType  `json:"first_category_type,omitempty"`
	FirstCategoryName     *string                          `json:"first_category_name,omitempty"`
	SecondCategoryType    ConversionLinkSecondCategoryType `json:"second_category_type,omitempty"`
	SecondCategoryName    *string                          `json:"second_category_name,omitempty"`
	LandingPageAccess     *LinkLandingPageAccess           `json:"landing_page_access,omitempty"`
	ConversionLinkNodes   *[]ConversionLinkAssetNodeStruct `json:"conversion_link_nodes,omitempty"`
	OptionalOgNodesIndex  *[]int64                         `json:"optional_og_nodes_index,omitempty"`
	Status                *int64                           `json:"status,omitempty"`
	Source                *int64                           `json:"source,omitempty"`
	CreateTime            *string                          `json:"create_time,omitempty"`
}
