/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 账户聚合信息
type AggregateAccountDetail struct {
	AccountId      *int64                   `json:"account_id,omitempty"`
	AccountName    *string                  `json:"account_name,omitempty"`
	IsRealPay      *bool                    `json:"is_real_pay,omitempty"`
	NoPayReason    *string                  `json:"no_pay_reason,omitempty"`
	PayTotalAmount *float64                 `json:"pay_total_amount,omitempty"`
	PayDetails     *[]InvalidPayLeadsDetail `json:"pay_details,omitempty"`
}
