/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// MaterialTaskStatus : 任务状态
type MaterialTaskStatus string

// List of MaterialTaskStatus
const (
	MaterialTaskStatus_UNKNOWN                     MaterialTaskStatus = "MATERIAL_TASK_STATUS_UNKNOWN"
	MaterialTaskStatus_WATERMARK_PROCESSING        MaterialTaskStatus = "MATERIAL_TASK_STATUS_WATERMARK_PROCESSING"
	MaterialTaskStatus_WATERMARK_SUCCESS           MaterialTaskStatus = "MATERIAL_TASK_STATUS_WATERMARK_SUCCESS"
	MaterialTaskStatus_WATERMARK_FAILED            MaterialTaskStatus = "MATERIAL_TASK_STATUS_WATERMARK_FAILED"
	MaterialTaskStatus_WATERMARK_EXCEPTION         MaterialTaskStatus = "MATERIAL_TASK_STATUS_WATERMARK_EXCEPTION"
	MaterialTaskStatus_WATERMARK_DELETED           MaterialTaskStatus = "MATERIAL_TASK_STATUS_WATERMARK_DELETED"
	MaterialTaskStatus_PREREVIEW_PROCESSING        MaterialTaskStatus = "MATERIAL_TASK_STATUS_PREREVIEW_PROCESSING"
	MaterialTaskStatus_PREREVIEW_HAS_REPAIR_DETAIL MaterialTaskStatus = "MATERIAL_TASK_STATUS_PREREVIEW_HAS_REPAIR_DETAIL"
	MaterialTaskStatus_PREREVIEW_NO_REPAIR_DETAIL  MaterialTaskStatus = "MATERIAL_TASK_STATUS_PREREVIEW_NO_REPAIR_DETAIL"
	MaterialTaskStatus_PREREVIEW_EXCEPTION         MaterialTaskStatus = "MATERIAL_TASK_STATUS_PREREVIEW_EXCEPTION"
)
