/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type AdvertiserConfigGetResponseData struct {
	CoverImageSnapshotType      CoverImageSnapshotType      `json:"cover_image_snapshot_type,omitempty"`
	MultiImageCollageStatus     MultiImageCollageStatus     `json:"multi_image_collage_status,omitempty"`
	MultiImageCollageAigcStatus MultiImageCollageAigcStatus `json:"multi_image_collage_aigc_status,omitempty"`
}
