/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 健康度模块汇总数据
type HealthyDataStruct struct {
	AccountId         *int64                 `json:"account_id,omitempty"`
	DynamicCreativeId *int64                 `json:"dynamic_creative_id,omitempty"`
	AdgroupId         *int64                 `json:"adgroup_id,omitempty"`
	List              *[]HealthyDetailStruct `json:"list,omitempty"`
}
