/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// OgCompletionType : 达成类型
type OgCompletionType string

// List of OgCompletionType
const (
	OgCompletionType_UNKNOWN                                      OgCompletionType = "OG_COMPLETION_TYPE_UNKNOWN"
	OgCompletionType_ENSURE_DEEP                                  OgCompletionType = "OG_COMPLETION_TYPE_ENSURE_DEEP"
	OgCompletionType_PERSONALIZATION_ENSURE_SHALLOW_OPTIMIZE_DEEP OgCompletionType = "OG_COMPLETION_TYPE_PERSONALIZATION_ENSURE_SHALLOW_OPTIMIZE_DEEP"
)
