/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 返回结构
type ProductCatalogsGetListStruct struct {
	ProductCatalogId        *int64                    `json:"product_catalog_id,omitempty"`
	ProductCatalogName      *string                   `json:"product_catalog_name,omitempty"`
	ProductCatalogType      DpaApiCatalogType         `json:"product_catalog_type,omitempty"`
	ProductCatalogVertical  CatalogVertical           `json:"product_catalog_vertical,omitempty"`
	ProductCatalogStatus    CatalogStatus             `json:"product_catalog_status,omitempty"`
	ProductRecommendMethods *[]ProductRecommendMethod `json:"product_recommend_methods,omitempty"`
	DeepLinkEnabled         *DeepLinkEnabled          `json:"deep_link_enabled,omitempty"`
}
