/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 图文链接结构
type MiniCardLinkStruct struct {
	MiniCardLinkDescription *string         `json:"mini_card_link_description,omitempty"`
	MiniCardLinkImage       *string         `json:"mini_card_link_image,omitempty"`
	MiniCardLinkButtonText  *string         `json:"mini_card_link_button_text,omitempty"`
	JumpInfo                *JumpinfoStruct `json:"jump_info,omitempty"`
}
