/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// TimeType : 时间类型
type TimeType string

// List of TimeType
const (
	TimeType_CREATED_TIME TimeType = "TIME_TYPE_CREATED_TIME"
	TimeType_ACTION_TIME  TimeType = "TIME_TYPE_ACTION_TIME"
)
