/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 修改广告组深度优化行为目标出价
type UpdateDeepConversionBehaviorBidItem struct {
	AdgroupId                 *int64 `json:"adgroup_id,omitempty"`
	DeepConversionBehaviorBid *int64 `json:"deep_conversion_behavior_bid,omitempty"`
}
