/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 表单组件元素
type ElementForm struct {
	Title *string `json:"title,omitempty"`
}
