/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type SaasMiniprogramPrereviewGetResponseData struct {
	TaskId        *string                   `json:"task_id,omitempty"`
	MiniProgramId *string                   `json:"mini_program_id,omitempty"`
	ProductId     *string                   `json:"product_id,omitempty"`
	ReviewResult  *int64                    `json:"review_result,omitempty"`
	RejectReasons *[]SaasRejectReasonStruct `json:"reject_reasons,omitempty"`
}
