/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// BackUpOption : 微信小程序/微信小游戏蹊径落地页开关选项
type BackUpOption string

// List of BackUpOption
const (
	BackUpOption_UNKNOWN     BackUpOption = "BACKUP_OPTION_UNKNOWN"
	BackUpOption_DEFAULT_ON  BackUpOption = "BACKUP_OPTION_DEFAULT_ON"
	BackUpOption_DEFAULT_OFF BackUpOption = "BACKUP_OPTION_DEFAULT_OFF"
)
