/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 处罚指标数据项
type PunishMetricsDataItem struct {
	PartitionTime           *int64  `json:"partition_time,omitempty"`
	OpsAdvertiserName       *string `json:"ops_advertiser_name,omitempty"`
	ZcAgentGroup            *string `json:"zc_agent_group,omitempty"`
	FirstLevelIndustryName  *string `json:"first_level_industry_name,omitempty"`
	SecondLevelIndustryName *string `json:"second_level_industry_name,omitempty"`
	IsPenalized             *int64  `json:"is_penalized,omitempty"`
	PenaltyReviewTotal      *int64  `json:"penalty_review_total,omitempty"`
	PenaltyReviewRejectCnt  *int64  `json:"penalty_review_reject_cnt,omitempty"`
	PenaltyRejectRate       *string `json:"penalty_reject_rate,omitempty"`
}
