/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 组件配置
type PageElement struct {
	ElementType                *string                     `json:"element_type,omitempty"`
	HeadOutsideMaterialConfig  *HeadOutsideMaterialConfig  `json:"head_outside_material_config,omitempty"`
	HeadVideoConfig            *HeadVideoConfig            `json:"head_video_config,omitempty"`
	HeadImageConfig            *HeadImageConfig            `json:"head_image_config,omitempty"`
	Head180PanoramaImageConfig *Head180PanoramaImageConfig `json:"head_180_panorama_image_config,omitempty"`
	HeadCarouselConfig         *HeadCarouselConfig         `json:"head_carousel_config,omitempty"`
	HeadTextConfig             *HeadTextConfig             `json:"head_text_config,omitempty"`
	BlockVideoConfig           *BlockVideoConfig           `json:"block_video_config,omitempty"`
	BlockImageConfig           *BlockImageConfig           `json:"block_image_config,omitempty"`
	BlockCarouselConfig        *BlockCarouselConfig        `json:"block_carousel_config,omitempty"`
	BlockTextConfig            *BlockTextConfig            `json:"block_text_config,omitempty"`
	BlockDividerConfig         *BlockDividerConfig         `json:"block_divider_config,omitempty"`
	BlockCustomPageConfig      *BlockCustomPageConfig      `json:"block_custom_page_config,omitempty"`
	BlockButtonConfig          *BlockButtonConfig          `json:"block_button_config,omitempty"`
	FixedButtonConfig          *FixedButtonConfig          `json:"fixed_button_config,omitempty"`
	RightFixedButtonConfig     *RightFixedButtonConfig     `json:"right_fixed_button_config,omitempty"`
	BlockShelfConfig           *BlockShelfConfig           `json:"block_shelf_config,omitempty"`
	BlockShelfGroupConfig      *BlockShelfGroupConfig      `json:"block_shelf_group_config,omitempty"`
}
