/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 子推荐方式
type SubMethod struct {
	SubMethodId          *int64  `json:"sub_method_id,omitempty"`
	SubMethodName        *string `json:"sub_method_name,omitempty"`
	SubMethodDescription *string `json:"sub_method_description,omitempty"`
}
