/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type PunishmentQueryGetRequest struct {
	OrderIdList      *[]string       `json:"order_id_list,omitempty"`
	AccountIdList    *[]int64        `json:"account_id_list,omitempty"`
	CompanyName      *string         `json:"company_name,omitempty"`
	IndustryIdList   *[]int64        `json:"industry_id_list,omitempty"`
	IllegalStartTime *int64          `json:"illegal_start_time,omitempty"`
	IllegalEndTime   *int64          `json:"illegal_end_time,omitempty"`
	IllegalNodeList  *[]string       `json:"illegal_node_list,omitempty"`
	ActionTypeList   *[]int64        `json:"action_type_list,omitempty"`
	StartTime        *int64          `json:"start_time,omitempty"`
	EndTime          *int64          `json:"end_time,omitempty"`
	LevelList        *[]int64        `json:"level_list,omitempty"`
	IllegalSceneList *[]string       `json:"illegal_scene_list,omitempty"`
	PageConf         *PunishPageConf `json:"page_conf,omitempty"`
}
