/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// LeadsUserType : 线索用户类型
type LeadsUserType string

// List of LeadsUserType
const (
	LeadsUserType_QQ              LeadsUserType = "USER_TYPE_QQ"
	LeadsUserType_QQ_MD5          LeadsUserType = "USER_TYPE_QQ_MD5"
	LeadsUserType_TEL             LeadsUserType = "USER_TYPE_TEL"
	LeadsUserType_TEL_MD5         LeadsUserType = "USER_TYPE_TEL_MD5"
	LeadsUserType_IDFA            LeadsUserType = "USER_TYPE_IDFA"
	LeadsUserType_IDFA_MD5        LeadsUserType = "USER_TYPE_IDFA_MD5"
	LeadsUserType_IMEI            LeadsUserType = "USER_TYPE_IMEI"
	LeadsUserType_IMEI_MD5        LeadsUserType = "USER_TYPE_IMEI_MD5"
	LeadsUserType_GDT_OPENID      LeadsUserType = "USER_TYPE_GDT_OPENID"
	LeadsUserType_MAC_ADDRESS     LeadsUserType = "USER_TYPE_MAC_ADDRESS"
	LeadsUserType_MAC_ADDRESS_MD5 LeadsUserType = "USER_TYPE_MAC_ADDRESS_MD5"
	LeadsUserType_OAID            LeadsUserType = "USER_TYPE_OAID"
	LeadsUserType_OAID_MD5        LeadsUserType = "USER_TYPE_OAID_MD5"
	LeadsUserType_WX_OPENID       LeadsUserType = "USER_TYPE_WX_OPENID"
	LeadsUserType_WX_UNIONID      LeadsUserType = "USER_TYPE_WX_UNIONID"
	LeadsUserType_OTHERS          LeadsUserType = "USER_TYPE_OTHERS"
)
