/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 小游戏跑量目标信息
type SmartDeliveryGoalMiniGamePromotionSpec struct {
	RegisterCost            *int64   `json:"register_cost,omitempty"`
	FirstDayPurchaseRoi     *float64 `json:"first_day_purchase_roi,omitempty"`
	FirstDayMonetizationRoi *float64 `json:"first_day_monetization_roi,omitempty"`
	SevenDayMonetizationRoi *float64 `json:"seven_day_monetization_roi,omitempty"`
	SevenDayPurchaseRoi     *float64 `json:"seven_day_purchase_roi,omitempty"`
	Day30PurchaseRoi        *float64 `json:"day30_purchase_roi,omitempty"`
}
