/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 动态内容广告属性
type DcaSpec struct {
	RecommendMethodIds *[]int64 `json:"recommend_method_ids,omitempty"`
	SetId              *string  `json:"set_id,omitempty"`
}
