/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

//
type ExpandFieldDefinition struct {
	FieldName   *string                      `json:"field_name,omitempty"`
	FieldNameCn *string                      `json:"field_name_cn,omitempty"`
	FieldType   QualificationExpandFieldType `json:"field_type,omitempty"`
	Required    *bool                        `json:"required,omitempty"`
	MaxLength   *int64                       `json:"max_length,omitempty"`
	Options     *[]string                    `json:"options,omitempty"`
}
