/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 修改广告组投放日期
type UpdateAdgroupDateItem struct {
	AdgroupId *int64  `json:"adgroup_id,omitempty"`
	BeginDate *string `json:"begin_date,omitempty"`
	EndDate   *string `json:"end_date,omitempty"`
	AccountId *int64  `json:"account_id,omitempty"`
}
