/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// ExpressCompany : 快递公司
type ExpressCompany string

// List of ExpressCompany
const (
	ExpressCompany_UNKNOWN            ExpressCompany = "UNKNOWN"
	ExpressCompany_SF_EXPRESS         ExpressCompany = "SF_EXPRESS"
	ExpressCompany_STO                ExpressCompany = "STO"
	ExpressCompany_YTO                ExpressCompany = "YTO"
	ExpressCompany_ZTO                ExpressCompany = "ZTO"
	ExpressCompany_BEST_EXPRESS       ExpressCompany = "BEST_EXPRESS"
	ExpressCompany_YUNDA_EXPRESS      ExpressCompany = "YUNDA_EXPRESS"
	ExpressCompany_TTK_EXPRESS        ExpressCompany = "TTK_EXPRESS"
	ExpressCompany_EMS                ExpressCompany = "EMS"
	ExpressCompany_CHINA_POST_EXPRESS ExpressCompany = "CHINA_POST_EXPRESS"
	ExpressCompany_JUST_IN_TIME       ExpressCompany = "JUST_IN_TIME"
	ExpressCompany_JD_EXPRESS         ExpressCompany = "JD_EXPRESS"
	ExpressCompany_DEPPON_EXPRESS     ExpressCompany = "DEPPON_EXPRESS"
)
