/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 返回结构
type AgencyBusinessUnitListByAccountGetListStruct struct {
	AccountId        *int64  `json:"account_id,omitempty"`
	OrganizationId   *int64  `json:"organization_id,omitempty"`
	BusinessUnitName *string `json:"business_unit_name,omitempty"`
}
