/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// FloatingZoneInfoType : 浮层卡片外显类型
type FloatingZoneInfoType string

// List of FloatingZoneInfoType
const (
	FloatingZoneInfoType_DEFAULT      FloatingZoneInfoType = "FLOATING_ZONE_INFO_DEFAULT"
	FloatingZoneInfoType_TYPE_NORMAL  FloatingZoneInfoType = "FLOATING_ZONE_INFO_TYPE_NORMAL"
	FloatingZoneInfoType_TYPE_PRODUCT FloatingZoneInfoType = "FLOATING_ZONE_INFO_TYPE_PRODUCT"
)
