/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 返回结构
type SceneSpecTagsGetListStruct struct {
	Id            *int64  `json:"id,omitempty"`
	Name          *string `json:"name,omitempty"`
	Description   *string `json:"description,omitempty"`
	ParentId      *int64  `json:"parent_id,omitempty"`
	TargetingName *string `json:"targeting_name,omitempty"`
}
