/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// ProductOwnerType : 商品所有者类型
type ProductOwnerType string

// List of ProductOwnerType
const (
	ProductOwnerType_SOP ProductOwnerType = "PRODUCT_OWNER_TYPE_SOP"
	ProductOwnerType_POP ProductOwnerType = "PRODUCT_OWNER_TYPE_POP"
)
