/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 分页内容
type PunishDetailPageConf struct {
	Page      *int64 `json:"page,omitempty"`
	PageSize  *int64 `json:"pageSize,omitempty"`
	TotalPage *int64 `json:"totalPage,omitempty"`
	TotalNum  *int64 `json:"totalNum,omitempty"`
}
