/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// ConversionLinkNodeApplicationType : 节点链路化应用类型
type ConversionLinkNodeApplicationType string

// List of ConversionLinkNodeApplicationType
const (
	ConversionLinkNodeApplicationType_AIDED_MODELING   ConversionLinkNodeApplicationType = "AIDED_MODELING"
	ConversionLinkNodeApplicationType_PREFACE_MODELING ConversionLinkNodeApplicationType = "PREFACE_MODELING"
	ConversionLinkNodeApplicationType_TIER_COLD_BOOT   ConversionLinkNodeApplicationType = "TIER_COLD_BOOT"
	ConversionLinkNodeApplicationType_TIER_REACH       ConversionLinkNodeApplicationType = "TIER_REACH"
	ConversionLinkNodeApplicationType_OG_MODELING      ConversionLinkNodeApplicationType = "OG_MODELING"
	ConversionLinkNodeApplicationType_ATTRIBUTION_NODE ConversionLinkNodeApplicationType = "ATTRIBUTION_NODE"
)
