/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 普通按钮组件配置
type BlockButtonConfig struct {
	Color              *string                           `json:"color,omitempty"`
	BackgroundColor    *string                           `json:"background_color,omitempty"`
	Content            *string                           `json:"content,omitempty"`
	HasIcon            *bool                             `json:"has_icon,omitempty"`
	ButtonSize         *string                           `json:"button_size,omitempty"`
	MarginTop          *int64                            `json:"margin_top,omitempty"`
	MarginBottom       *int64                            `json:"margin_bottom,omitempty"`
	ConvertUnknown     *ConvertInfoConfigUnknown         `json:"convert_unknown,omitempty"`
	ConvertDownload    *ConvertInfoConfigDownload        `json:"convert_download,omitempty"`
	ConvertLink        *ConvertInfoConfigLink            `json:"convert_link,omitempty"`
	ConvertWeapp       *ConvertInfoConfigMiniProgram     `json:"convert_weapp,omitempty"`
	ConvertGh          *ConvertInfoConfigOfficialAccount `json:"convert_gh,omitempty"`
	ConvertFollowVideo *ConvertInfoConfigFollowVideo     `json:"convert_followVideo,omitempty"`
}
