/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 推广资产属性信息
type PropertyStruct struct {
	PropertyName  PromotedAssetAttrKey    `json:"property_name,omitempty"`
	PropertyValue *[]string               `json:"property_value,omitempty"`
	PropertyClass MarketingAssetAttrClass `json:"property_class,omitempty"`
	PropertyCn    *string                 `json:"property_cn,omitempty"`
}
