/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type LocalStorePackagesDeleteResponseData struct {
	LocalStorePackageId *int64 `json:"local_store_package_id,omitempty"`
}
