/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// OfficialPageType : 官方落地页类型
type OfficialPageType string

// List of OfficialPageType
const (
	OfficialPageType_DEFAULT_H5         OfficialPageType = "XJ_DEFAULT_H5"
	OfficialPageType_ANDROID_APP_H5     OfficialPageType = "XJ_ANDROID_APP_H5"
	OfficialPageType_IOS_APP_H5         OfficialPageType = "XJ_IOS_APP_H5"
	OfficialPageType_ANDROID_IOS_APP_H5 OfficialPageType = "XJ_ANDROID_IOS_APP_H5"
	OfficialPageType_WEBSITE_H5         OfficialPageType = "XJ_WEBSITE_H5"
)
