/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// RTA策略绑定信息
type RtaTargetBindList struct {
	Page          *int64  `json:"Page,omitempty"`
	Size          *int64  `json:"Size,omitempty"`
	OuterTargetId *string `json:"OuterTargetId,omitempty"`
}
