/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 审核拒绝的组件组合
type RejectComponentComposeInfoStruct struct {
	RejectMessage               *string                          `json:"reject_message,omitempty"`
	ComponentComposeElementList *[]ComponentComposeElementStruct `json:"component_compose_element_list,omitempty"`
}
