/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 图片组件元素
type ElementImage struct {
	ImageIdList *[]string `json:"image_id_list,omitempty"`
}
