/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 图文复合组件
type ElementShelf struct {
	ShelfSpec *[]ShelfSpecStruct `json:"shelf_spec,omitempty"`
}
