/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// ShootingScene : 拍摄场景
type ShootingScene string

// List of ShootingScene
const (
	ShootingScene_IN   ShootingScene = "SHOOTING_SCENE_IN"
	ShootingScene_OUT  ShootingScene = "SHOOTING_SCENE_OUT"
	ShootingScene_BOTH ShootingScene = "SHOOTING_SCENE_BOTH"
)
