/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 元素预审结果明细
type PreReviewDetailStruct struct {
	SiteSet            PreReviewSiteSetDefinitionString `json:"site_set,omitempty"`
	PreReviewResult    GroupRiskLevel                   `json:"pre_review_result,omitempty"`
	RejectReasonDetail *[]RejectReasonDetailStruct      `json:"reject_reason_detail,omitempty"`
}
