/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/antihax/optional"
	"github.com/tencentad/marketing-api-go-sdk/pkg/ads/v3"
	"github.com/tencentad/marketing-api-go-sdk/pkg/api/v3"
	"github.com/tencentad/marketing-api-go-sdk/pkg/config/v3"
	"github.com/tencentad/marketing-api-go-sdk/pkg/errors"
	"github.com/tencentad/marketing-api-go-sdk/pkg/model/v3"
)

type UnionPositionPackagesGetExample struct {
	TAds                         *ads.SDKClient
	AccessToken                  string
	AccountId                    int64
	UnionPositionPackagesGetOpts *api.UnionPositionPackagesGetOpts
}

func (e *UnionPositionPackagesGetExample) Init() {
	e.AccessToken = "YOUR ACCESS TOKEN"
	e.TAds = ads.Init(&config.SDKConfig{
		AccessToken: e.AccessToken,
		IsDebug:     true,
	})
	e.AccountId = int64(0)
	e.UnionPositionPackagesGetOpts = &api.UnionPositionPackagesGetOpts{

		Fields: optional.NewInterface([]string{"union_package_id", "union_package_name", "union_package_type", "union_position_id_list", "created_time", "last_modified_time"}),
	}
}

func (e *UnionPositionPackagesGetExample) RunExample() (model.UnionPositionPackagesGetResponseData, http.Header, error) {
	tads := e.TAds
	// change ctx as needed
	ctx := *tads.Ctx
	return tads.UnionPositionPackages().Get(ctx, e.AccountId, e.UnionPositionPackagesGetOpts)
}

func main() {
	e := &UnionPositionPackagesGetExample{}
	e.Init()
	response, headers, err := e.RunExample()
	if err != nil {
		if resErr, ok := err.(errors.ResponseError); ok {
			errStr, _ := json.Marshal(resErr)
			fmt.Println("Response error:", string(errStr))
		} else {
			fmt.Println("Error:", err)
		}
	}
	fmt.Println("Response data:", response)
	fmt.Println("Headers:", headers)
}
