/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/tencentad/marketing-api-go-sdk/pkg/ads/v3"
	"github.com/tencentad/marketing-api-go-sdk/pkg/api/v3"
	"github.com/tencentad/marketing-api-go-sdk/pkg/config/v3"
	"github.com/tencentad/marketing-api-go-sdk/pkg/errors"
	"github.com/tencentad/marketing-api-go-sdk/pkg/model/v3"
)

type MergeFundTypeFundStatementsDetailedGetExample struct {
	TAds                                       *ads.SDKClient
	AccessToken                                string
	AccountId                                  int64
	FundType                                   string
	DateRange                                  model.DateRangeTransaction
	MergeFundTypeFundStatementsDetailedGetOpts *api.MergeFundTypeFundStatementsDetailedGetOpts
}

func (e *MergeFundTypeFundStatementsDetailedGetExample) Init() {
	e.AccessToken = "YOUR ACCESS TOKEN"
	e.TAds = ads.Init(&config.SDKConfig{
		AccessToken: e.AccessToken,
		IsDebug:     true,
	})
	e.AccountId = 789
	e.FundType = "fundType_example"
	e.DateRange = model.DateRangeTransaction{}
	e.MergeFundTypeFundStatementsDetailedGetOpts = &api.MergeFundTypeFundStatementsDetailedGetOpts{}
}

func (e *MergeFundTypeFundStatementsDetailedGetExample) RunExample() (model.MergeFundTypeFundStatementsDetailedGetResponseData, http.Header, error) {
	tads := e.TAds
	// change ctx as needed
	ctx := *tads.Ctx
	return tads.MergeFundTypeFundStatementsDetailed().Get(ctx, e.AccountId, e.FundType, e.DateRange, e.MergeFundTypeFundStatementsDetailedGetOpts)
}

func main() {
	e := &MergeFundTypeFundStatementsDetailedGetExample{}
	e.Init()
	response, headers, err := e.RunExample()
	if err != nil {
		if resErr, ok := err.(errors.ResponseError); ok {
			errStr, _ := json.Marshal(resErr)
			fmt.Println("Response error:", string(errStr))
		} else {
			fmt.Println("Error:", err)
		}
	}
	fmt.Println("Response data:", response)
	fmt.Println("Headers:", headers)
}
