/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/antihax/optional"
	"github.com/tencentad/marketing-api-go-sdk/pkg/ads"
	"github.com/tencentad/marketing-api-go-sdk/pkg/api"
	"github.com/tencentad/marketing-api-go-sdk/pkg/config"
	"github.com/tencentad/marketing-api-go-sdk/pkg/errors"
	"github.com/tencentad/marketing-api-go-sdk/pkg/model"
)

type CampaignsGetExample struct {
	TAds             *ads.SDKClient
	AccessToken      string
	AccountId        int64
	CampaignsGetOpts *api.CampaignsGetOpts
}

func (e *CampaignsGetExample) Init() {
	e.AccessToken = "YOUR ACCESS TOKEN"
	e.TAds = ads.Init(&config.SDKConfig{
		AccessToken: e.AccessToken,
		IsDebug:     true,
	})
	e.AccountId = int64(0)
	e.CampaignsGetOpts = &api.CampaignsGetOpts{

		Filtering: optional.NewInterface([]model.FilteringStruct{{
			Field:    "promoted_object_type",
			Operator: "EQUALS",
			Values:   &[]string{"PROMOTED_OBJECT_TYPE_APP_IOS"},
		}}),

		Fields: optional.NewInterface([]string{"campaign_id", "campaign_name"}),
	}
}

func (e *CampaignsGetExample) RunExample() (model.CampaignsGetResponseData, http.Header, error) {
	tads := e.TAds
	// change ctx as needed
	ctx := *tads.Ctx
	return tads.Campaigns().Get(ctx, e.AccountId, e.CampaignsGetOpts)
}

func main() {
	e := &CampaignsGetExample{}
	e.Init()
	response, headers, err := e.RunExample()
	if err != nil {
		if resErr, ok := err.(errors.ResponseError); ok {
			errStr, _ := json.Marshal(resErr)
			fmt.Println("Response error:", string(errStr))
		} else {
			fmt.Println("Error:", err)
		}
	}
	fmt.Println("Response data:", response)
	fmt.Println("Headers:", headers)
}
