/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/antihax/optional"
	"github.com/tencentad/marketing-api-go-sdk/pkg/ads"
	"github.com/tencentad/marketing-api-go-sdk/pkg/api"
	"github.com/tencentad/marketing-api-go-sdk/pkg/config"
	"github.com/tencentad/marketing-api-go-sdk/pkg/errors"
	"github.com/tencentad/marketing-api-go-sdk/pkg/model"
)

type PagesGetExample struct {
	TAds               *ads.SDKClient
	AccessToken        string
	AccountId          int64
	PromotedObjectType string
	PagesGetOpts       *api.PagesGetOpts
}

func (e *PagesGetExample) Init() {
	e.AccessToken = "YOUR ACCESS TOKEN"
	e.TAds = ads.Init(&config.SDKConfig{
		AccessToken: e.AccessToken,
		IsDebug:     true,
	})
	e.AccountId = int64(0)
	e.PromotedObjectType = "PROMOTED_OBJECT_TYPE_LINK"
	e.PagesGetOpts = &api.PagesGetOpts{

		Fields: optional.NewInterface([]string{"page_id", "page_name", "preview_url", "created_time", "last_modified_time", "promoted_object_id", "page_type"}),
	}
}

func (e *PagesGetExample) RunExample() (model.PagesGetResponseData, *http.Response, error) {
	tads := e.TAds
	// change ctx as needed
	ctx := *tads.Ctx
	return tads.Pages().Get(ctx, e.AccountId, e.PromotedObjectType, e.PagesGetOpts)
}

func main() {
	e := &PagesGetExample{}
	e.Init()
	response, httpResponse, err := e.RunExample()
	if err != nil {
		if resErr, ok := err.(errors.ResponseError); ok {
			errStr, _ := json.Marshal(resErr)
			fmt.Println("Response error:", string(errStr))
		} else {
			fmt.Println("Error:", err)
		}
	}
	fmt.Println("Response data:", response)
	fmt.Println("Http response:", httpResponse)
}
