/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 数据源分发详情
type SingleUpdateFail struct {
	UserActionSetId *int64                      `json:"user_action_set_id,omitempty"`
	Scenes          *[]SingleUpdateFailedScenes `json:"scenes,omitempty"`
	FailReason      *string                     `json:"fail_reason,omitempty"`
}
