/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// DnAssetType : 资产类型
type DnAssetType string

// List of DnAssetType
const (
	DnAssetType_DATA_SOURCE DnAssetType = "ASSET_TYPE_DN_DATA_SOURCE"
	DnAssetType_DATA_SET    DnAssetType = "ASSET_TYPE_DN_DATA_SET"
	DnAssetType_FILE        DnAssetType = "ASSET_TYPE_DN_FILE"
)
