/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 基础轮播图组件元素<br>        图片尺寸: 普通轮播样式: 750*(300-1125), <br>        卡片轮播样式: 512*(288-920)
type SliderSpec struct {
	ImageIdList *[]string `json:"image_id_list,omitempty"`
	Width       *int64    `json:"width,omitempty"`
	Height      *int64    `json:"height,omitempty"`
	SliderStyle *int64    `json:"slider_style,omitempty"`
	BgColor     *string   `json:"bg_color,omitempty"`
}
