/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 电话组件
type PhoneComponentValueStruct struct {
	Id *int64 `json:"id,omitempty"`
}
