/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 图文复合组件配置
type ImageTextItemStruct struct {
	BorderColor      *string                    `json:"border_color,omitempty"`
	TitleColor       *string                    `json:"title_color,omitempty"`
	DescColor        *string                    `json:"desc_color,omitempty"`
	BgColor          *string                    `json:"bg_color,omitempty"`
	JumpMode         CanvasImageTextJumpMode    `json:"jump_mode,omitempty"`
	MaterialId       *string                    `json:"material_id,omitempty"`
	Title            *string                    `json:"title,omitempty"`
	Desc             *string                    `json:"desc,omitempty"`
	SubElemType      CanvasImageTextElementType `json:"sub_elem_type,omitempty"`
	GhSpec           *FloatGhSpec               `json:"gh_spec,omitempty"`
	EnterpriseWxSpec *FloatEnterpriseWxSpec     `json:"enterprise_wx_spec,omitempty"`
}
