/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// AdLockStatus : 锁定状态
type AdLockStatus string

// List of AdLockStatus
const (
	AdLockStatus_LOCKED   AdLockStatus = "ADLOCKSTATUS_LOCKED"
	AdLockStatus_UNLOCKED AdLockStatus = "ADLOCKSTATUS_UNLOCKED"
)
