/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type PlayablePagesAddResponseData struct {
	LandingPageId          *string `json:"landing_page_id,omitempty"`
	PlayablePageId         *string `json:"playable_page_id,omitempty"`
	PlayablePageMaterialId *string `json:"playable_page_material_id,omitempty"`
}
