/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// OperationType : 文件操作类型
type OperationType string

// List of OperationType
const (
	OperationType_CREATE OperationType = "CREATE"
	OperationType_DELETE OperationType = "DELETE"
	OperationType_APPEND OperationType = "APPEND"
	OperationType_REDUCE OperationType = "REDUCE"
)
