/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// TransferType : 转账类型
type TransferType string

// List of TransferType
const (
	TransferType_AGENCY_TO_ADVERTISER TransferType = "AGENCY_TO_ADVERTISER"
	TransferType_ADVERTISER_TO_AGENCY TransferType = "ADVERTISER_TO_AGENCY"
)
