/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 微信搜一搜品牌专区-doc区块-头部背景
type WxSearchBrandAreaDocZoneHeader struct {
	Type_    *int64                              `json:"type,omitempty"`
	ImageUrl *string                             `json:"image_url,omitempty"`
	VideoUrl *string                             `json:"video_url,omitempty"`
	JumpInfo *WxSearchBrandAreaDocJumpInfo       `json:"jump_info,omitempty"`
	Link     *WxSearchBrandAreaDocZoneHeaderLink `json:"link,omitempty"`
}
