/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// DpApiDestinationType : 落地页类型
type DpApiDestinationType string

// List of DpApiDestinationType
const (
	DpApiDestinationType_DEFAULT                      DpApiDestinationType = "PAGE_TYPE_DEFAULT"
	DpApiDestinationType_TSA_APP                      DpApiDestinationType = "PAGE_TYPE_TSA_APP"
	DpApiDestinationType_TSA_WEB_NONE_ECOMMERCE       DpApiDestinationType = "PAGE_TYPE_TSA_WEB_NONE_ECOMMERCE"
	DpApiDestinationType_CANVAS_WECHAT                DpApiDestinationType = "PAGE_TYPE_CANVAS_WECHAT"
	DpApiDestinationType_MINI_PROGRAM_WECHAT          DpApiDestinationType = "PAGE_TYPE_MINI_PROGRAM_WECHAT"
	DpApiDestinationType_FENGYE_ECOMMERCE             DpApiDestinationType = "PAGE_TYPE_FENGYE_ECOMMERCE"
	DpApiDestinationType_MINI_GAME_WECHAT             DpApiDestinationType = "PAGE_TYPE_MINI_GAME_WECHAT"
	DpApiDestinationType_MINI_PROGRAM_QQ              DpApiDestinationType = "PAGE_TYPE_MINI_PROGRAM_QQ"
	DpApiDestinationType_MINI_PROGRAM_CANVAS_WECHAT   DpApiDestinationType = "PAGE_TYPE_MINI_PROGRAM_CANVAS_WECHAT"
	DpApiDestinationType_MINI_GAME_QQ                 DpApiDestinationType = "PAGE_TYPE_MINI_GAME_QQ"
	DpApiDestinationType_ARTICAL_WECHAT               DpApiDestinationType = "PAGE_TYPE_ARTICAL_WECHAT"
	DpApiDestinationType_MOMENTS_SIMPLE_NATIVE_WECHAT DpApiDestinationType = "PAGE_TYPE_MOMENTS_SIMPLE_NATIVE_WECHAT"
	DpApiDestinationType_FULL_SCREEN_WECHAT           DpApiDestinationType = "PAGE_TYPE_FULL_SCREEN_WECHAT"
	DpApiDestinationType_WECHAT_CHANNELS              DpApiDestinationType = "PAGE_TYPE_WECHAT_CHANNELS"
)
