/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 广告组天报表查询条件
type TaskTypeWechatAdgroupDailyReportSpec struct {
	Date *string `json:"date,omitempty"`
}
