/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 深浅成本趋势
type CpaEffectDataTrendsItem struct {
	Rank      *int64         `json:"rank,omitempty"`
	TargetCpa *[]PointStruct `json:"target_cpa,omitempty"`
	RealCpa   *[]PointStruct `json:"real_cpa,omitempty"`
}
