/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 本地门店信息
type LocalAdsSpecRead struct {
	ShopName         *string `json:"shop_name,omitempty"`
	Address          *string `json:"address,omitempty"`
	Telphone         *string `json:"telphone,omitempty"`
	SystemIndustryId *string `json:"system_industry_id,omitempty"`
}
