/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// ExEcoLocalBusinessMode : 附近推模式
type ExEcoLocalBusinessMode string

// List of ExEcoLocalBusinessMode
const (
	ExEcoLocalBusinessMode_DEFAULT           ExEcoLocalBusinessMode = "LOCAL_BUSINESS_MODE_DEFAULT"
	ExEcoLocalBusinessMode_LEADS_COUPON      ExEcoLocalBusinessMode = "LOCAL_BUSINESS_MODE_LEADS_COUPON"
	ExEcoLocalBusinessMode_LEADS_RESERVATION ExEcoLocalBusinessMode = "LOCAL_BUSINESS_MODE_LEADS_RESERVATION"
)
