/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type XijingPageInteractiveAddResponseData struct {
	List *[]CreatePageResponse `json:"list,omitempty"`
}
