/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 罗卡行为标签
type LocardBehaviorsListItem struct {
	Id   *string `json:"id,omitempty"`
	Text *string `json:"text,omitempty"`
}
