/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 不支持的站点
type UnsupportSite struct {
	SiteSet []string `json:"site_set,omitempty"`
}
