/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// AutoDerivedCreativeStatus : 广告自动衍生视频创意状态
type AutoDerivedCreativeStatus string

// List of AutoDerivedCreativeStatus
const (
	AutoDerivedCreativeStatus_DEFAULT   AutoDerivedCreativeStatus = "AUTO_DERIVED_CREATIVE_STATUS_DEFAULT"
	AutoDerivedCreativeStatus_INITIATED AutoDerivedCreativeStatus = "AUTO_DERIVED_CREATIVE_STATUS_INITIATED"
	AutoDerivedCreativeStatus_SUCCESS   AutoDerivedCreativeStatus = "AUTO_DERIVED_CREATIVE_STATUS_SUCCESS"
	AutoDerivedCreativeStatus_FAIL      AutoDerivedCreativeStatus = "AUTO_DERIVED_CREATIVE_STATUS_FAIL"
	AutoDerivedCreativeStatus_RUNNING   AutoDerivedCreativeStatus = "AUTO_DERIVED_CREATIVE_STATUS_RUNNING"
)
