/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 微信搜一搜品牌专区-doc区块-账号信息
type WxSearchBrandAreaDocAccountInfo struct {
	Type_    *int64                                     `json:"type,omitempty"`
	List     *[]WxSearchBrandAreaDocAccountInfoListItem `json:"list,omitempty"`
	MoreInfo *WxSearchBrandAreaDocAccountInfoMoreInfo   `json:"more_info,omitempty"`
}
