/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 诊断详情-定向明细
type DetailTargetDetailStruct struct {
	ExpandTargetingOpened *bool          `json:"expand_targeting_opened,omitempty"`
	Score                 *int64         `json:"score,omitempty"`
	Trends                *[]PointStruct `json:"trends,omitempty"`
	Conclusion            *string        `json:"conclusion,omitempty"`
}
