/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 场景
type SingleDispatchScene struct {
	Scene      FileAvailableScene  `json:"scene,omitempty"`
	FileId     *int64              `json:"file_id,omitempty"`
	AttachInfo *DispatchAttachInfo `json:"attach_info,omitempty"`
}
