/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 诊断详情-成本明细
type DetailCpaDetailStruct struct {
	EffectData       *CpaEffectDataStruct `json:"effect_data,omitempty"`
	EffectDataTrends *CpaEffectDataTrends `json:"effect_data_trends,omitempty"`
}
