/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 品牌形象
type AdCreativeBrand struct {
	BrandName        *string                 `json:"brand_name,omitempty"`
	BrandImg         *string                 `json:"brand_img,omitempty"`
	BrandDescription *string                 `json:"brand_description,omitempty"`
	MainJumpInfo     *[]LandingPageStructure `json:"main_jump_info,omitempty"`
}
