/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 微信小程序原生页
type DpAlitaPageSpec struct {
	ButtonTips  *string `json:"button_tips,omitempty"`
	CouponTitle *string `json:"coupon_title,omitempty"`
	BeginDate   *string `json:"begin_date,omitempty"`
	EndDate     *string `json:"end_date,omitempty"`
}
