/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// DynamicAdTemplateOwnershipType : 动态商品模板所属类型
type DynamicAdTemplateOwnershipType string

// List of DynamicAdTemplateOwnershipType
const (
	DynamicAdTemplateOwnershipType_PRIVATE_TEMPLATE DynamicAdTemplateOwnershipType = "PRIVATE_TEMPLATE"
	DynamicAdTemplateOwnershipType_PUBLIC_TEMPLATE  DynamicAdTemplateOwnershipType = "PUBLIC_TEMPLATE"
)
