/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// ConversionOptimizationGoal : 深度优化ROI目标，深度优化行为目标和深度优化ROI目标仅可填写其中一个
type ConversionOptimizationGoal string

// List of ConversionOptimizationGoal
const (
	ConversionOptimizationGoal_NONE                   ConversionOptimizationGoal = "GOAL_NONE"
	ConversionOptimizationGoal_7DAYPURCHASEROAS_      ConversionOptimizationGoal = "GOAL_7DAY_PURCHASE_ROAS"
	ConversionOptimizationGoal_15DAYPURCHASEROAS_     ConversionOptimizationGoal = "GOAL_15DAY_PURCHASE_ROAS"
	ConversionOptimizationGoal_30DAYPURCHASEROAS_     ConversionOptimizationGoal = "GOAL_30DAY_PURCHASE_ROAS"
	ConversionOptimizationGoal_60DAYPURCHASEROAS_     ConversionOptimizationGoal = "GOAL_60DAY_PURCHASE_ROAS"
	ConversionOptimizationGoal_30DAYMONETIZATIONROAS_ ConversionOptimizationGoal = "GOAL_30DAY_MONETIZATION_ROAS"
	ConversionOptimizationGoal_30DAYORDERROAS_        ConversionOptimizationGoal = "GOAL_30DAY_ORDER_ROAS"
	ConversionOptimizationGoal_1DAYPURCHASEROAS_      ConversionOptimizationGoal = "GOAL_1DAY_PURCHASE_ROAS"
	ConversionOptimizationGoal_1DAYMONETIZATIONROAS_  ConversionOptimizationGoal = "GOAL_1DAY_MONETIZATION_ROAS"
	ConversionOptimizationGoal_3DAYPURCHASEROAS_      ConversionOptimizationGoal = "GOAL_3DAY_PURCHASE_ROAS"
	ConversionOptimizationGoal_3DAYMONETIZATIONROAS_  ConversionOptimizationGoal = "GOAL_3DAY_MONETIZATION_ROAS"
	ConversionOptimizationGoal_7DAYMONETIZATIONROAS_  ConversionOptimizationGoal = "GOAL_7DAY_MONETIZATION_ROAS"
	ConversionOptimizationGoal_15DAYMONETIZATIONROAS_ ConversionOptimizationGoal = "GOAL_15DAY_MONETIZATION_ROAS"
)
