/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 枫叶信息
type FengyeSpec struct {
	Title    *string `json:"title,omitempty"`
	FengyeId *string `json:"fengye_id,omitempty"`
}
