/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type AdcreativeTemplatePreviewsGetRequest struct {
	AdgroupId         *int64   `json:"adgroup_id,omitempty"`
	AdIdList          *[]int64 `json:"ad_id_list,omitempty"`
	DynamicCreativeId *int64   `json:"dynamic_creative_id,omitempty"`
	Adgroup           *Adgroup `json:"adgroup,omitempty"`
	AdList            *[]Ad    `json:"ad_list,omitempty"`
	AccountId         *int64   `json:"account_id,omitempty"`
}
