/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 元素预审结果明细
type PreReviewDetailStruct struct {
	SiteSet            IntSiteSetDefinition        `json:"site_set,omitempty"`
	PreReviewResult    GroupRiskLevel              `json:"pre_review_result,omitempty"`
	RejectReasonDetail *[]RejectReasonDetailStruct `json:"reject_reason_detail,omitempty"`
}
