/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// WechatPromotedObjectType : 推广目标类型
type WechatPromotedObjectType string

// List of WechatPromotedObjectType
const (
	WechatPromotedObjectType_APP_ANDROID      WechatPromotedObjectType = "PROMOTED_OBJECT_TYPE_APP_ANDROID"
	WechatPromotedObjectType_APP_IOS          WechatPromotedObjectType = "PROMOTED_OBJECT_TYPE_APP_IOS"
	WechatPromotedObjectType_ECOMMERCE        WechatPromotedObjectType = "PROMOTED_OBJECT_TYPE_ECOMMERCE"
	WechatPromotedObjectType_LINK_WECHAT      WechatPromotedObjectType = "PROMOTED_OBJECT_TYPE_LINK_WECHAT"
	WechatPromotedObjectType_LOCAL_ADS_WECHAT WechatPromotedObjectType = "PROMOTED_OBJECT_TYPE_LOCAL_ADS_WECHAT"
	WechatPromotedObjectType_LEAD_AD          WechatPromotedObjectType = "PROMOTED_OBJECT_TYPE_LEAD_AD"
	WechatPromotedObjectType_MINI_GAME_WECHAT WechatPromotedObjectType = "PROMOTED_OBJECT_TYPE_MINI_GAME_WECHAT"
)
