/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 微信搜一搜品牌专区-doc区块数据
type WxSearchBrandAreaItemsItemDataMap struct {
	ZoneHeader   *WxSearchBrandAreaDocZoneHeader   `json:"zone_header,omitempty"`
	BasicInfo    *WxSearchBrandAreaDocBasicInfo    `json:"basic_info,omitempty"`
	AccountInfo  *WxSearchBrandAreaDocAccountInfo  `json:"account_info,omitempty"`
	ActivityInfo *WxSearchBrandAreaDocActivityInfo `json:"activity_info,omitempty"`
}
