/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// WechatChannelsCoverImgShowType : 视频号封面图显示类型
type WechatChannelsCoverImgShowType string

// List of WechatChannelsCoverImgShowType
const (
	WechatChannelsCoverImgShowType_DEFAULT WechatChannelsCoverImgShowType = "COVER_IMG_SHOW_TYPE_DEFAULT"
	WechatChannelsCoverImgShowType_TITLE   WechatChannelsCoverImgShowType = "COVER_IMG_SHOW_TYPE_TITLE"
	WechatChannelsCoverImgShowType_CENTER  WechatChannelsCoverImgShowType = "COVER_IMG_SHOW_TYPE_CENTER"
)
