/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type UserPropertySetsGetResponseData struct {
	List []UserPropertySet `json:"list,omitempty"`
}
