/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// LinkPageType : 文字链跳转类型类型
type LinkPageType string

// List of LinkPageType
const (
	LinkPageType_NOT_USED                       LinkPageType = "LINK_PAGE_TYPE_NOT_USED"
	LinkPageType_DEFAULT                        LinkPageType = "LINK_PAGE_TYPE_DEFAULT"
	LinkPageType_CANVAS_WECHAT                  LinkPageType = "LINK_PAGE_TYPE_CANVAS_WECHAT"
	LinkPageType_ARTICAL_WECHAT                 LinkPageType = "LINK_PAGE_TYPE_ARTICAL_WECHAT"
	LinkPageType_MINI_PROGRAM_WECHAT            LinkPageType = "LINK_PAGE_TYPE_MINI_PROGRAM_WECHAT"
	LinkPageType_MINI_PROGRAM_CANVAS_WECHAT     LinkPageType = "LINK_PAGE_TYPE_MINI_PROGRAM_CANVAS_WECHAT"
	LinkPageType_MINI_GAME_WECHAT               LinkPageType = "LINK_PAGE_TYPE_MINI_GAME_WECHAT"
	LinkPageType_FENGYE_ECOMMERCE               LinkPageType = "LINK_PAGE_TYPE_FENGYE_ECOMMERCE"
	LinkPageType_XJ_ANDROID_APP_H5              LinkPageType = "LINK_PAGE_TYPE_XJ_ANDROID_APP_H5"
	LinkPageType_XJ_IOS_APP_H5                  LinkPageType = "LINK_PAGE_TYPE_XJ_IOS_APP_H5"
	LinkPageType_XJ_WEBSITE_H5                  LinkPageType = "LINK_PAGE_TYPE_XJ_WEBSITE_H5"
	LinkPageType_WECHAT_MOMENTS_SIMPLE_NATIVE   LinkPageType = "LINK_PAGE_TYPE_WECHAT_MOMENTS_SIMPLE_NATIVE"
	LinkPageType_CHANNELS                       LinkPageType = "LINK_PAGE_TYPE_CHANNELS"
	LinkPageType_CHANNELS_WATCH_LIVE            LinkPageType = "LINK_PAGE_TYPE_CHANNELS_WATCH_LIVE"
	LinkPageType_CHANNELS_RESERVE_LIVE          LinkPageType = "LINK_PAGE_TYPE_CHANNELS_RESERVE_LIVE"
	LinkPageType_CHANNELS_FOLLOW_CARD           LinkPageType = "LINK_PAGE_TYPE_CHANNELS_FOLLOW_CARD"
	LinkPageType_WECHAT_APPOINTMENT_CARD        LinkPageType = "LINK_PAGE_TYPE_WECHAT_APPOINTMENT_CARD"
	LinkPageType_WECHAT_CONSULT                 LinkPageType = "LINK_PAGE_TYPE_WECHAT_CONSULT"
	LinkPageType_WECOM_CONSULT                  LinkPageType = "LINK_PAGE_TYPE_WECOM_CONSULT"
	LinkPageType_WECHAT_FOCUS_DAILOG            LinkPageType = "LINK_PAGE_TYPE_WECHAT_FOCUS_DAILOG"
	LinkPageType_WECHAT_MOMENTS_SUBSCRIPTION    LinkPageType = "LINK_PAGE_TYPE_WECHAT_MOMENTS_SUBSCRIPTION"
	LinkPageType_WECHAT_RED_PACKET_COVER        LinkPageType = "LINK_PAGE_TYPE_WECHAT_RED_PACKET_COVER"
	LinkPageType_WECHAT_VIDEO_TOPIC             LinkPageType = "LINK_PAGE_TYPE_WECHAT_VIDEO_TOPIC"
	LinkPageType_WECHAT_OFFICIAL_ACCOUNT_DETAIL LinkPageType = "LINK_PAGE_TYPE_WECHAT_OFFICIAL_ACCOUNT_DETAIL"
	LinkPageType_XJ_QUICK                       LinkPageType = "LINK_PAGE_TYPE_XJ_QUICK"
	LinkPageType_YOUZAN_WECHAT_MINIPROGRAM      LinkPageType = "LINK_PAGE_TYPE_YOUZAN_WECHAT_MINIPROGRAM"
	LinkPageType_WEIMOB_WECHAT_MINIPROGRAM      LinkPageType = "LINK_PAGE_TYPE_WEIMOB_WECHAT_MINIPROGRAM"
	LinkPageType_ANDROID_DIRECT_DOWNLOAD        LinkPageType = "LINK_PAGE_TYPE_ANDROID_DIRECT_DOWNLOAD"
	LinkPageType_LINGQUE_H5                     LinkPageType = "LINK_PAGE_TYPE_LINGQUE_H5"
	LinkPageType_LINGQUE_MINI_PROGRAM           LinkPageType = "LINK_PAGE_TYPE_LINGQUE_MINI_PROGRAM"
	LinkPageType_WECHAT_CHANNELS_SHOP_PRODUCT   LinkPageType = "LINK_PAGE_TYPE_WECHAT_CHANNELS_SHOP_PRODUCT"
)
