/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 流量充足度、竞争宽松度趋势变化
type CompeteSurroundingsStruct struct {
	DisplayFlag        *bool                          `json:"display_flag,omitempty"`
	TrafficSufficiency *TrafficSufficiencyTrendStruct `json:"traffic_sufficiency,omitempty"`
	CompeteIntense     *CompeteIntenseTrendStruct     `json:"compete_intense,omitempty"`
}
