/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// Schema列选项定义
type MktSchemaDefineOption struct {
	Name   *string          `json:"name,omitempty"`
	ColKey FileSchemaColKey `json:"col_key,omitempty"`
}
