/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// AppealStatus : 申诉状态。详见AppealStatus枚举类型
type AppealStatus string

// List of AppealStatus
const (
	AppealStatus_COMPLETED AppealStatus = "APPEAL_STATUS_COMPLETED"
	AppealStatus_PENDING   AppealStatus = "APPEAL_STATUS_PENDING"
	AppealStatus_CANCEL    AppealStatus = "APPEAL_STATUS_CANCEL"
)
