/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// DynamicAdTemplateType : 动态商品模板类型
type DynamicAdTemplateType string

// List of DynamicAdTemplateType
const (
	DynamicAdTemplateType_IMAGE_TEMPLATE DynamicAdTemplateType = "DYNAMIC_AD_IMAGE_TEMPLATE"
	DynamicAdTemplateType_VIDEO_TEMPLATE DynamicAdTemplateType = "DYNAMIC_AD_VIDEO_TEMPLATE"
)
