/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// CatalogIndustry : 商品库行业类型
type CatalogIndustry string

// List of CatalogIndustry
const (
	CatalogIndustry_INDUSTRY_TYPE_ECOMMERCE CatalogIndustry = "INDUSTRY_TYPE_ECOMMERCE"
)
