/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// SizeAdjustmentMethodEnum : 调整尺寸方式：高斯模糊、指定颜色、智能裁剪、智能取图、指定图片
type SizeAdjustmentMethodEnum string

// List of SizeAdjustmentMethodEnum
const (
	SizeAdjustmentMethodEnum_GAUSSIAN    SizeAdjustmentMethodEnum = "GAUSSIAN"
	SizeAdjustmentMethodEnum_COLOR       SizeAdjustmentMethodEnum = "COLOR"
	SizeAdjustmentMethodEnum_SMART_CLIP  SizeAdjustmentMethodEnum = "SMART_CLIP"
	SizeAdjustmentMethodEnum_SMART_IMAGE SizeAdjustmentMethodEnum = "SMART_IMAGE"
	SizeAdjustmentMethodEnum_IMAGE       SizeAdjustmentMethodEnum = "IMAGE"
)
