/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 选择按钮结构
type ChosenButtonComponentValueStruct struct {
	LeftButtonText  *string                 `json:"left_button_text,omitempty"`
	LeftJumpInfo    *[]LandingPageStructure `json:"left_jump_info,omitempty"`
	RightButtonText *string                 `json:"right_button_text,omitempty"`
	RightJumpInfo   *[]LandingPageStructure `json:"right_jump_info,omitempty"`
}
