/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 动态创意（升级版）信息
type ProgramCreativeInfo struct {
	MaterialDeriveId *int64  `json:"material_derive_id,omitempty"`
	BidMode          BidMode `json:"bid_mode,omitempty"`
}
