/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 组合人群简单规则
type SimpleRule struct {
	AudienceId *int64 `json:"audience_id,omitempty"`
	TimeWindow *int64 `json:"time_window,omitempty"`
}
