/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 计划结构
type CampaignUpdateSpec struct {
	CampaignName string `json:"campaign_name,omitempty"`
}
