/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 礼包码，微信朋友圈广告创意形式需要填写
type AppGiftPackCode struct {
	Code *string `json:"code,omitempty"`
	Tips *string `json:"tips,omitempty"`
}
