/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 版位调价
type SiteSetPackageStruct struct {
	SiteSet            *[]string `json:"site_set,omitempty"`
	BidCoefficient     *float64  `json:"bid_coefficient,omitempty"`
	DeepBidCoefficient *float64  `json:"deep_bid_coefficient,omitempty"`
}
