/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 商标
type AdcreativeCorporate struct {
	CorporateName *string `json:"corporate_name,omitempty"`
	CorporateImg  *string `json:"corporate_img,omitempty"`
}
