/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// LabelType : 创意标签类型
type LabelType string

// List of LabelType
const (
	LabelType_UNKNOWN       LabelType = "LABEL_TYPE_UNKNOWN"
	LabelType_COMMON        LabelType = "LABEL_TYPE_COMMON"
	LabelType_PROMOTIONAL   LabelType = "LABEL_TYPE_PROMOTIONAL"
	LabelType_CUSTOMIZETEXT LabelType = "LABEL_TYPE_CUSTOMIZETEXT"
	LabelType_ICON          LabelType = "LABEL_TYPE_ICON"
	LabelType_DYNAMIC       LabelType = "LABEL_TYPE_DYNAMIC"
)
