/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 小程序信息
type SimplifyMiniProgramSpec struct {
	MiniProgramId   *string `json:"mini_program_id,omitempty"`
	MiniProgramPath *string `json:"mini_program_path,omitempty"`
}
