/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// TargetingSourceType : 定向包来源，自建或者来自分享
type TargetingSourceType string

// List of TargetingSourceType
const (
	TargetingSourceType_CREATE TargetingSourceType = "TARGETING_SOURCE_TYPE_CREATE"
	TargetingSourceType_SHARE  TargetingSourceType = "TARGETING_SOURCE_TYPE_SHARE"
)
