/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// CompeteAttribution : 归因CODE
type CompeteAttribution string

// List of CompeteAttribution
const (
	CompeteAttribution_ECPM                 CompeteAttribution = "ATTRIBUTE_ECPM"
	CompeteAttribution_BID                  CompeteAttribution = "ATTRIBUTE_BID"
	CompeteAttribution_PCTR                 CompeteAttribution = "ATTRIBUTE_PCTR"
	CompeteAttribution_TARGETING            CompeteAttribution = "ATTRIBUTE_TARGETING"
	CompeteAttribution_COLD_START           CompeteAttribution = "ATTRIBUTE_COLD_START"
	CompeteAttribution_EXPERIMENT           CompeteAttribution = "ATTRIBUTE_EXPERIMENT"
	CompeteAttribution_CAMPAIGN             CompeteAttribution = "ATTRIBUTE_CAMPAIGN"
	CompeteAttribution_EXPERIENCE_OTHERS    CompeteAttribution = "ATTRIBUTE_EXPERIENCE_OTHERS"
	CompeteAttribution_OTHERS               CompeteAttribution = "ATTRIBUTE_OTHERS"
	CompeteAttribution_EXPERIENCE_PRODUCT   CompeteAttribution = "ATTRIBUTE_EXPERIENCE_PRODUCT"
	CompeteAttribution_EXPERIENCE_CREATIVE  CompeteAttribution = "ATTRIBUTE_EXPERIENCE_CREATIVE"
	CompeteAttribution_LEARNING_FAILED      CompeteAttribution = "ATTRIBUTE_LEARNING_FAILED"
	CompeteAttribution_EXPERIENCE_FEEDBACK  CompeteAttribution = "ATTRIBUTE_EXPERIENCE_FEEDBACK"
	CompeteAttribution_EXPERIENCE_FRESHNESS CompeteAttribution = "ATTRIBUTE_EXPERIENCE_FRESHNESS"
	CompeteAttribution_BUDGET               CompeteAttribution = "ATTRIBUTE_BUDGET"
	CompeteAttribution_INNER_COMPETE        CompeteAttribution = "ATTRIBUTE_INNER_COMPETE"
	CompeteAttribution_PCVR                 CompeteAttribution = "ATTRIBUTE_PCVR"
	CompeteAttribution_OPT_KNOCK_OUT        CompeteAttribution = "ATTRIBUTE_OPT_KNOCK_OUT"
)
