/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// LbsPoiType : LBS兴趣点类型
type LbsPoiType string

// List of LbsPOIType
const (
	LbsPoiType_ALL       LbsPoiType = "ALL"
	LbsPoiType_TRAVEL_IN LbsPoiType = "TRAVEL_IN"
)
