/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// AssetType : 资产类型
type AssetType string

// List of AssetType
const (
	AssetType_NDMP                         AssetType = "ASSET_TYPE_NDMP"
	AssetType_XIJING                       AssetType = "ASSET_TYPE_XIJING"
	AssetType_CANVAS_WECHAT                AssetType = "ASSET_TYPE_CANVAS_WECHAT"
	AssetType_CANVAS_IMAGE                 AssetType = "ASSET_TYPE_CANVAS_IMAGE"
	AssetType_CANVAS_VIDEO                 AssetType = "ASSET_TYPE_CANVAS_VIDEO"
	AssetType_FENGYE                       AssetType = "ASSET_TYPE_FENGYE"
	AssetType_DYNAMIC_AD_TEMPLATE          AssetType = "ASSET_TYPE_DYNAMIC_AD_TEMPLATE"
	AssetType_AD_QUALIFICATION             AssetType = "ASSET_TYPE_AD_QUALIFICATION"
	AssetType_CATALOG                      AssetType = "ASSET_TYPE_CATALOG"
	AssetType_ACTION_SET                   AssetType = "ASSET_TYPE_ACTION_SET"
	AssetType_CONVERSION_SPEC              AssetType = "ASSET_TYPE_CONVERSION_SPEC"
	AssetType_UNION_PACKAGE                AssetType = "ASSET_TYPE_UNION_PACKAGE"
	AssetType_ACCOUNT_WECHAT_CANVAS        AssetType = "ASSET_TYPE_ACCOUNT_WECHAT_CANVAS"
	AssetType_PROFILE                      AssetType = "ASSET_TYPE_PROFILE"
	AssetType_LOCAL_STORE                  AssetType = "ASSET_TYPE_LOCAL_STORE"
	AssetType_INTERACTIVE_PRIVATE_TEMPLATE AssetType = "ASSET_TYPE_INTERACTIVE_PRIVATE_TEMPLATE"
	AssetType_DN_DATA_SOURCE               AssetType = "ASSET_TYPE_DN_DATA_SOURCE"
	AssetType_DN_DATA_SET                  AssetType = "ASSET_TYPE_DN_DATA_SET"
	AssetType_DN_FILE                      AssetType = "ASSET_TYPE_DN_FILE"
	AssetType_SEARCH_BRAND_AREA            AssetType = "ASSET_TYPE_SEARCH_BRAND_AREA"
	AssetType_UNION_APP_URL_CHANNEL        AssetType = "ASSET_TYPE_UNION_APP_URL_CHANNEL"
)
