/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// BidwordMatchType : 关键词匹配方式
type BidwordMatchType string

// List of BidwordMatchType
const (
	BidwordMatchType_EXACT_MATCH  BidwordMatchType = "EXACT_MATCH"
	BidwordMatchType_WIDE_MATCH   BidwordMatchType = "WIDE_MATCH"
	BidwordMatchType_WORD_MATCH   BidwordMatchType = "WORD_MATCH"
	BidwordMatchType_PHRASE_MATCH BidwordMatchType = "PHRASE_MATCH"
)
