/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 数据集详情
type SingleDataSet struct {
	DataSetId *int64 `json:"data_set_id,omitempty"`
	EnvType   *int64 `json:"env_type,omitempty"`
}
