/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type UnionPositionPackagesAddResponseData struct {
	UnionPackageId *int64 `json:"union_package_id,omitempty"`
}
