/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 授权成功信息
type DataNexusGrantSuccessListItem struct {
	AssetId    *int64  `json:"asset_id,omitempty"`
	FailReason *string `json:"fail_reason,omitempty"`
}
