/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 标签
type RuleTagChild struct {
	TagId    *int64             `json:"tag_id,omitempty"`
	ParentId *int64             `json:"parent_id,omitempty"`
	Value    *string            `json:"value,omitempty"`
	Name     *string            `json:"name,omitempty"`
	Level    *int64             `json:"level,omitempty"`
	Type_    RuleLabTag         `json:"type,omitempty"`
	Children *[]RuleTagChildStr `json:"children,omitempty"`
}
