/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type ProgrammedAddResponseData struct {
	MaterialDeriveId *int64 `json:"material_derive_id,omitempty"`
}
