/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// LinkNameTypeMp : 链接名称类型
type LinkNameTypeMp string

// List of LinkNameTypeMP
const (
	LinkNameTypeMp_VIEW_DETAILS            LinkNameTypeMp = "VIEW_DETAILS"
	LinkNameTypeMp_GET_COUPONS             LinkNameTypeMp = "GET_COUPONS"
	LinkNameTypeMp_MAKE_AN_APPOINTMENT     LinkNameTypeMp = "MAKE_AN_APPOINTMENT"
	LinkNameTypeMp_BUY_NOW                 LinkNameTypeMp = "BUY_NOW"
	LinkNameTypeMp_GO_SHOPPING             LinkNameTypeMp = "GO_SHOPPING"
	LinkNameTypeMp_ENTER_MINI_PROGRAM      LinkNameTypeMp = "ENTER_MINI_PROGRAM"
	LinkNameTypeMp_ENTER_MINI_GAME         LinkNameTypeMp = "ENTER_MINI_GAME"
	LinkNameTypeMp_APPLY_NOW               LinkNameTypeMp = "APPLY_NOW"
	LinkNameTypeMp_BOOK_NOW                LinkNameTypeMp = "BOOK_NOW"
	LinkNameTypeMp_RESERVATION_BUY         LinkNameTypeMp = "RESERVATION_BUY"
	LinkNameTypeMp_CONSULT_NOW             LinkNameTypeMp = "CONSULT_NOW"
	LinkNameTypeMp_BOOK_DRIVE              LinkNameTypeMp = "BOOK_DRIVE"
	LinkNameTypeMp_ENTER_OFFICIAL_ACCOUNTS LinkNameTypeMp = "ENTER_OFFICIAL_ACCOUNTS"
	LinkNameTypeMp_PLAY_NOW                LinkNameTypeMp = "PLAY_NOW"
	LinkNameTypeMp_OPEN_MINI_GAME          LinkNameTypeMp = "OPEN_MINI_GAME"
	LinkNameTypeMp_DOWNLOAD_APP            LinkNameTypeMp = "DOWNLOAD_APP"
	LinkNameTypeMp_DOWNLOAD_GAME           LinkNameTypeMp = "DOWNLOAD_GAME"
	LinkNameTypeMp_GET_SAMPLES             LinkNameTypeMp = "GET_SAMPLES"
	LinkNameTypeMp_GET_IT_NOW              LinkNameTypeMp = "GET_IT_NOW"
	LinkNameTypeMp_BUY_ASAP                LinkNameTypeMp = "BUY_ASAP"
	LinkNameTypeMp_DOWNLOAD_NOW            LinkNameTypeMp = "DOWNLOAD_NOW"
	LinkNameTypeMp_VIEW_APPS               LinkNameTypeMp = "VIEW_APPS"
	LinkNameTypeMp_MORE_INFO               LinkNameTypeMp = "MORE_INFO"
	LinkNameTypeMp_GET_VOUCHERS            LinkNameTypeMp = "GET_VOUCHERS"
	LinkNameTypeMp_FOLLOW_OFFICIAL_ACCOUNT LinkNameTypeMp = "FOLLOW_OFFICIAL_ACCOUNT"
	LinkNameTypeMp_READ_NOVELS             LinkNameTypeMp = "READ_NOVELS"
	LinkNameTypeMp_GO_TO_JD                LinkNameTypeMp = "GO_TO_JD"
	LinkNameTypeMp_GO_TO_PDD               LinkNameTypeMp = "GO_TO_PDD"
	LinkNameTypeMp_GO_TO_SUNING            LinkNameTypeMp = "GO_TO_SUNING"
	LinkNameTypeMp_GO_TO_VIP               LinkNameTypeMp = "GO_TO_VIP"
	LinkNameTypeMp_GO_TO_XIAOHONGSHU       LinkNameTypeMp = "GO_TO_XIAOHONGSHU"
	LinkNameTypeMp_GO_TO_KUAISHOU          LinkNameTypeMp = "GO_TO_KUAISHOU"
	LinkNameTypeMp_WATCH_LIVE              LinkNameTypeMp = "WATCH_LIVE"
	LinkNameTypeMp_RESERVE_NOW             LinkNameTypeMp = "RESERVE_NOW"
)
