/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type LocalStoresDeleteRequest struct {
	AccountId *int64    `json:"account_id,omitempty"`
	PoiList   *[]string `json:"poi_list,omitempty"`
}
