/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 落地页适用场景描述
type LandingPageMediaQuery struct {
	MediaType LandingPageMediaType `json:"media_type,omitempty"`
}
