/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 手工调整视频
type ManualAdjustment struct {
	SizeAdjustment   *SizeAdjustment   `json:"size_adjustment,omitempty"`
	LengthAdjustment *LengthAdjustment `json:"length_adjustment,omitempty"`
	MusicAdjustment  *MusicAdjustment  `json:"music_adjustment,omitempty"`
}
