/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// ImageOperationType : 操作类型
type ImageOperationType string

// List of ImageOperationType
const (
	ImageOperationType_CROP_CUSTOMIZED            ImageOperationType = "OPERATION_TYPE_CROP_CUSTOMIZED"
	ImageOperationType_CROP_SMART                 ImageOperationType = "OPERATION_TYPE_CROP_SMART"
	ImageOperationType_RESIZE                     ImageOperationType = "OPERATION_TYPE_RESIZE"
	ImageOperationType_CROP_CUSTOMIZED_AND_RESIZE ImageOperationType = "OPERATION_TYPE_CROP_CUSTOMIZED_AND_RESIZE"
)
