/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type CreativeSampleProductsGetRequest struct {
	AccountId        *int64       `json:"account_id,omitempty"`
	ProductCatalogId *int64       `json:"product_catalog_id,omitempty"`
	ProductOuterIds  *[]string    `json:"product_outer_ids,omitempty"`
	ProductSeriesId  *int64       `json:"product_series_id,omitempty"`
	TemplateId       *int64       `json:"template_id,omitempty"`
	TemplateType     TemplateType `json:"template_type,omitempty"`
	ImageId          *string      `json:"image_id,omitempty"`
	VideoId          *string      `json:"video_id,omitempty"`
	ProductFields    *[]string    `json:"product_fields,omitempty"`
	Limit            *int64       `json:"limit,omitempty"`
}
