/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// AccountType : 账号类型
type AccountType string

// List of AccountType
const (
	AccountType_UNKNOWN           AccountType = "ACCOUNT_TYPE_UNKNOWN"
	AccountType_ADVERTISER        AccountType = "ACCOUNT_TYPE_ADVERTISER"
	AccountType_AGENCY            AccountType = "ACCOUNT_TYPE_AGENCY"
	AccountType_DSP               AccountType = "ACCOUNT_TYPE_DSP"
	AccountType_DEVELOPER         AccountType = "ACCOUNT_TYPE_DEVELOPER"
	AccountType_MEMBER            AccountType = "ACCOUNT_TYPE_MEMBER"
	AccountType_EXTERNAL_SUPPLIER AccountType = "ACCOUNT_TYPE_EXTERNAL_SUPPLIER"
	AccountType_TDC               AccountType = "ACCOUNT_TYPE_TDC"
	AccountType_TONE              AccountType = "ACCOUNT_TYPE_TONE"
	AccountType_BM                AccountType = "ACCOUNT_TYPE_BM"
	AccountType_DATA_NEXUS        AccountType = "ACCOUNT_TYPE_DATA_NEXUS"
)
