/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// MarketingScene : 营销场景
type MarketingScene string

// List of MarketingScene
const (
	MarketingScene_DEFAULT                                    MarketingScene = "DEFAULT"
	MarketingScene_GAME_RESERVATION                           MarketingScene = "GAME_RESERVATION"
	MarketingScene_GAME_PROMOTION                             MarketingScene = "GAME_PROMOTION"
	MarketingScene_APP_ACTIVE_PROMOTION                       MarketingScene = "APP_ACTIVE_PROMOTION"
	MarketingScene_ECOMMERCE_GOODS_DIRECT_PURCHASE_DAILY      MarketingScene = "ECOMMERCE_GOODS_DIRECT_PURCHASE_DAILY"
	MarketingScene_ECOMMERCE_CONSUMER_COLLECT_CLUES_DAILY     MarketingScene = "ECOMMERCE_CONSUMER_COLLECT_CLUES_DAILY"
	MarketingScene_ECOMMERCE_CONSUMER_ADD_FOLLOWERS_DAILY     MarketingScene = "ECOMMERCE_CONSUMER_ADD_FOLLOWERS_DAILY"
	MarketingScene_ECOMMERCE_CONSUMER_OFFICIAL_ACCOUNTS_DAILY MarketingScene = "ECOMMERCE_CONSUMER_OFFICIAL_ACCOUNTS_DAILY"
	MarketingScene_ECOMMERCE_GOODS_LIVE_PURCHASE_DAILY        MarketingScene = "ECOMMERCE_GOODS_LIVE_PURCHASE_DAILY"
	MarketingScene_ECOMMERCE_CONSUMER_CHANNELS_DAILY          MarketingScene = "ECOMMERCE_CONSUMER_CHANNELS_DAILY"
)
