/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 出价修改信息
type BidAmountSpec struct {
	BidAmount *int64 `json:"bid_amount,omitempty"`
}
