/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 任务所需条件
type TaskSpec struct {
	ReportTaskSpec                               *ReportTaskSpec                               `json:"report_task_spec,omitempty"`
	TaskTypeAdHourlyReportSpec                   *TaskTypeAdHourlyReportSpec                   `json:"task_type_ad_hourly_report_spec,omitempty"`
	TaskTypeWechatMomentsAdgroupHourlyReportSpec *TaskTypeWechatMomentsAdgroupHourlyReportSpec `json:"task_type_wechat_moments_adgroup_hourly_report_spec,omitempty"`
	TaskTypeWechatAdgroupHourlyReportSpec        *TaskTypeWechatAdgroupHourlyReportSpec        `json:"task_type_wechat_adgroup_hourly_report_spec,omitempty"`
	TaskTypeWechatAdgroupDailyReportSpec         *TaskTypeWechatAdgroupDailyReportSpec         `json:"task_type_wechat_adgroup_daily_report_spec,omitempty"`
	TaskTypeWechatAdHourlyReportSpec             *TaskTypeWechatAdHourlyReportSpec             `json:"task_type_wechat_ad_hourly_report_spec,omitempty"`
	TaskTypeWechatAdDailyReportSpec              *TaskTypeWechatAdDailyReportSpec              `json:"task_type_wechat_ad_daily_report_spec,omitempty"`
	TaskTypeWechatAdvertisingDataSpec            *TaskTypeWechatAdvertisingDataSpec            `json:"task_type_wechat_advertising_data_spec,omitempty"`
	TaskTypeWechatPoiHourlyReportSpec            *TaskTypeWechatPoiHourlyReportSpec            `json:"task_type_wechat_poi_hourly_report_spec,omitempty"`
	TaskTypeCreateAndroidChannelPackageSpec      *TaskTypeCreateAndroidChannelPackageSpec      `json:"task_type_create_android_channel_package_spec,omitempty"`
	TaskTypeUpdateAndroidChannelPackageSpec      *TaskTypeUpdateAndroidChannelPackageSpec      `json:"task_type_update_android_channel_package_spec,omitempty"`
	TaskTypeCreateAndroidUnionChannelPackageSpec *TaskTypeCreateAndroidUnionChannelPackageSpec `json:"task_type_create_android_union_channel_package_spec,omitempty"`
	TaskTypeUpdateAndroidUnionChannelPackageSpec *TaskTypeUpdateAndroidUnionChannelPackageSpec `json:"task_type_update_android_union_channel_package_spec,omitempty"`
	TaskTypeUnionPositionReportSpec              *TaskTypeUnionPositionReportSpec              `json:"task_type_union_position_report_spec,omitempty"`
	TaskTypeReviewElementPrereviewResultSpec     *TaskTypeReviewElementPrereviewResultSpec     `json:"task_type_review_element_prereview_result_spec,omitempty"`
	TaskTypeMassiveKeywordRecommendSpec          *TaskTypeMassiveKeywordRecommendSpec          `json:"task_type_massive_keyword_recommend_spec,omitempty"`
	TaskTypeSearchDownloadAllSpec                *TaskTypeSearchDownloadAllSpec                `json:"task_type_search_download_all_spec,omitempty"`
	AdcleanerUpdateAdgroupConfiguredStatusSpec   *AdcleanerUpdateAdgroupConfiguredStatusSpec   `json:"adcleaner_update_adgroup_configured_status_spec,omitempty"`
	AdcleanerDeleteAdgroupSpec                   *AdcleanerDeleteAdgroupSpec                   `json:"adcleaner_delete_adgroup_spec,omitempty"`
}
