/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 商品标题组件
type MdpaTitleComponentValueStruct struct {
	Title *string `json:"title,omitempty"`
}
