/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 分页配置信息
type Conf struct {
	Page        *int64 `json:"page,omitempty"`
	PageSize    *int64 `json:"page_size,omitempty"`
	TotalNumber *int64 `json:"total_number,omitempty"`
	TotalPage   *int64 `json:"total_page,omitempty"`
}
