/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type AdgroupsGetNegativewordResponseData struct {
	AdgroupErrorList *[]string                    `json:"adgroup_error_list,omitempty"`
	AdgroupList      *[]NegativeWordAdgroupStruct `json:"adgroup_list,omitempty"`
}
