/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// LbsType : LBS类型
type LbsType string

// List of LbsType
const (
	LbsType_LBSTYPE_BUSINESS LbsType = "LBSTYPE_BUSINESS"
	LbsType_LBSTYPE_LANDMARK LbsType = "LBSTYPE_LANDMARK"
	LbsType_LBSTYPE_SUBWAY   LbsType = "LBSTYPE_SUBWAY"
	LbsType_POI              LbsType = "POI"
	LbsType_CROSS_CITY       LbsType = "CROSS_CITY"
	LbsType_CUSTOM_LOCATION  LbsType = "CUSTOM_LOCATION"
)
