/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type LeadsCallCreateRequest struct {
	AccountId    *int64  `json:"account_id,omitempty"`
	LeadsId      *int64  `json:"leads_id,omitempty"`
	UserId       *int64  `json:"user_id,omitempty"`
	CalleeNumber *string `json:"callee_number,omitempty"`
	RequestId    *string `json:"request_id,omitempty"`
	Version      *string `json:"version,omitempty"`
}
