/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type VideomakerVideocapturesAddResponseData struct {
	Code          *int64                `json:"code,omitempty"`
	VideoCaptures *[]VideoCaptureStruct `json:"video_captures,omitempty"`
}
