/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 支持落地页类型结构
type SupportPageTypeStructPermit struct {
	PageType            *string                    `json:"page_type,omitempty"`
	Description         *string                    `json:"description,omitempty"`
	SupportLinkNameType *SupportLinkNameTypePermit `json:"support_link_name_type,omitempty"`
	SupportLinkPageType *SupportLinkPageTypePermit `json:"support_link_page_type,omitempty"`
}
