/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 导入的线索信息结构
type LeadsImportInfoStruct struct {
	OuterLeadsId             *string             `json:"outer_leads_id,omitempty"`
	LeadsId                  *int64              `json:"leads_id,omitempty"`
	LeadsTel                 *string             `json:"leads_tel,omitempty"`
	LeadsQq                  *int64              `json:"leads_qq,omitempty"`
	LeadsWechat              *string             `json:"leads_wechat,omitempty"`
	ClickId                  *string             `json:"click_id,omitempty"`
	LeadsType                LeadCluesLeadsType  `json:"leads_type,omitempty"`
	LeadsUserId              *string             `json:"leads_user_id,omitempty"`
	LeadsUserType            LeadsUserType       `json:"leads_user_type,omitempty"`
	LeadsUserWechatAppid     *string             `json:"leads_user_wechat_appid,omitempty"`
	LeadsActionTime          *string             `json:"leads_action_time,omitempty"`
	LeadsName                *string             `json:"leads_name,omitempty"`
	LeadsGender              LeadCluesGenderType `json:"leads_gender,omitempty"`
	LeadsEmail               *string             `json:"leads_email,omitempty"`
	LeadsArea                *string             `json:"leads_area,omitempty"`
	Bundle                   *string             `json:"bundle,omitempty"`
	LeadsConvertType         *string             `json:"leads_convert_type,omitempty"`
	LeadsIneffectReason      *string             `json:"leads_ineffect_reason,omitempty"`
	OuterLeadsConvertType    *string             `json:"outer_leads_convert_type,omitempty"`
	OuterLeadsIneffectReason *string             `json:"outer_leads_ineffect_reason,omitempty"`
	OuterLeadsComefrom       OuterLeadsComeFrom  `json:"outer_leads_comefrom,omitempty"`
	Memo                     *string             `json:"memo,omitempty"`
	WechatAgencyId           *string             `json:"wechat_agency_id,omitempty"`
	LeadsAge                 *string             `json:"leads_age,omitempty"`
	LeadsIdNumber            *string             `json:"leads_id_number,omitempty"`
	LeadsNationality         *string             `json:"leads_nationality,omitempty"`
	LeadsAddress             *string             `json:"leads_address,omitempty"`
	LeadsCompany             *string             `json:"leads_company,omitempty"`
	LeadsProfession          *string             `json:"leads_profession,omitempty"`
	LeadsWorkingYears        *string             `json:"leads_working_years,omitempty"`
	LeadsPageId              *string             `json:"leads_page_id,omitempty"`
	LeadsPageName            *string             `json:"leads_page_name,omitempty"`
	LeadsPageUrl             *string             `json:"leads_page_url,omitempty"`
}
