/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// DpApiReportLevel : 报表类型
type DpApiReportLevel string

// List of DpApiReportLevel
const (
	DpApiReportLevel_ADVERTISER_WECHAT DpApiReportLevel = "REPORT_LEVEL_ADVERTISER_WECHAT"
	DpApiReportLevel_ADGROUP_WECHAT    DpApiReportLevel = "REPORT_LEVEL_ADGROUP_WECHAT"
)
