/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type ImagesUpdateRequest struct {
	ImageId     *string `json:"image_id,omitempty"`
	Description *string `json:"description,omitempty"`
	AccountId   *int64  `json:"account_id,omitempty"`
}
