/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 应用下载组件元素
type CanvasAppDownloadSpecType struct {
	Title          *string                   `json:"title,omitempty"`
	FontColor      *string                   `json:"font_color,omitempty"`
	BgColor        *string                   `json:"bg_color,omitempty"`
	PaddingTop     *int64                    `json:"padding_top,omitempty"`
	PaddingBottom  *int64                    `json:"padding_bottom,omitempty"`
	AppIosSpec     *CanvasAppIosSpecType     `json:"app_ios_spec,omitempty"`
	AppAndroidSpec *CanvasAppAndroidSpecType `json:"app_android_spec,omitempty"`
}
