/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 文件Schema列
type SchemeCol struct {
	ColKey FileSchemaColKey `json:"col_key,omitempty"`
	Index  *int64           `json:"index,omitempty"`
}
