/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 修改推广计划客户设置的状态
type UpdateCampaignConfiguredStatusItem struct {
	CampaignId       *int64   `json:"campaign_id,omitempty"`
	ConfiguredStatus AdStatus `json:"configured_status,omitempty"`
}
