/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// oCPC/oCPM 深度辅助优化-优化转化行为
type DeepConversionBehaviorAdvancedSpec struct {
	Goal      OptimizationGoal `json:"goal,omitempty"`
	BidAmount *int64           `json:"bid_amount,omitempty"`
}
