/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// LocalStoreCustomerProfileGender : 门店经营信息用户画像性别
type LocalStoreCustomerProfileGender string

// List of LocalStoreCustomerProfileGender
const (
	LocalStoreCustomerProfileGender_UNKNOWN  LocalStoreCustomerProfileGender = "UNKNOWN"
	LocalStoreCustomerProfileGender_MALE     LocalStoreCustomerProfileGender = "MALE"
	LocalStoreCustomerProfileGender_FEMALE   LocalStoreCustomerProfileGender = "FEMALE"
	LocalStoreCustomerProfileGender_BALANCED LocalStoreCustomerProfileGender = "BALANCED"
)
