/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 短视频结构
type ShortVideoStruct struct {
	ShortVideo1 *int64 `json:"short_video1,omitempty"`
	ShortVideo2 *int64 `json:"short_video2,omitempty"`
}
