/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type PropertySetsAddResponseData struct {
	PropertySetId *int64 `json:"property_set_id,omitempty"`
}
