/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 返回结构
type OuterCluesAddListStruct struct {
	OuterLeadsId *string `json:"outer_leads_id,omitempty"`
}
