/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// DnFileDispatchStatus : 文件分发状态
type DnFileDispatchStatus string

// List of DnFileDispatchStatus
const (
	DnFileDispatchStatus_UN_DISPATCHED DnFileDispatchStatus = "UN_DISPATCHED"
	DnFileDispatchStatus_DISPATCHING   DnFileDispatchStatus = "DISPATCHING"
	DnFileDispatchStatus_DISPATCHED    DnFileDispatchStatus = "DISPATCHED"
	DnFileDispatchStatus_BE_CANCELLING DnFileDispatchStatus = "BE_CANCELLING"
)
