/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 广告清理工具删除广告
type AdcleanerDeleteAdgroupSpec struct {
	AdcleanData *AdcleanDeleteAdgroupData `json:"adclean_data,omitempty"`
}
