/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type LabelAudiencesAddResponseData struct {
	AudienceId *int64 `json:"audience_id,omitempty"`
}
