/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// LeadCluesLeadsType : 线索类型
type LeadCluesLeadsType string

// List of LeadCluesLeadsType
const (
	LeadCluesLeadsType_FORM                LeadCluesLeadsType = "LEADS_TYPE_FORM"
	LeadCluesLeadsType_ONLINE_CONSULT      LeadCluesLeadsType = "LEADS_TYPE_ONLINE_CONSULT"
	LeadCluesLeadsType_MAKE_PHONE_CALL     LeadCluesLeadsType = "LEADS_TYPE_MAKE_PHONE_CALL"
	LeadCluesLeadsType_PHONE               LeadCluesLeadsType = "LEADS_TYPE_PHONE"
	LeadCluesLeadsType_PROMOTION_COUPON    LeadCluesLeadsType = "LEADS_TYPE_PROMOTION_COUPON"
	LeadCluesLeadsType_INTELLIGENT_TOOL    LeadCluesLeadsType = "LEADS_TYPE_INTELLIGENT_TOOL"
	LeadCluesLeadsType_LOTTERY             LeadCluesLeadsType = "LEADS_TYPE_LOTTERY"
	LeadCluesLeadsType_LANDING_PAGE_CLICK  LeadCluesLeadsType = "LEADS_TYPE_LANDING_PAGE_CLICK"
	LeadCluesLeadsType_ONE_CLICK_AUTHORIZE LeadCluesLeadsType = "LEADS_TYPE_ONE_CLICK_AUTHORIZE"
	LeadCluesLeadsType_PAGE_SCAN_CODE      LeadCluesLeadsType = "LEADS_TYPE_PAGE_SCAN_CODE"
	LeadCluesLeadsType_PROMOTION_FOLLOW    LeadCluesLeadsType = "LEADS_TYPE_PROMOTION_FOLLOW"
)
