/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 返回结构
type GameFeatureTagsGetListStruct struct {
	Id         *int64  `json:"id,omitempty"`
	Name       *string `json:"name,omitempty"`
	Type_      *string `json:"type,omitempty"`
	ParentId   *int64  `json:"parent_id,omitempty"`
	ParentName *string `json:"parent_name,omitempty"`
	ParentType *string `json:"parent_type,omitempty"`
}
