/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// AdCreativeSource : 创意来源
type AdCreativeSource string

// List of AdCreativeSource
const (
	AdCreativeSource_SOURCE_NORMAL    AdCreativeSource = "AD_CREATIVE_SOURCE_NORMAL"
	AdCreativeSource_AUTO_DERIVE      AdCreativeSource = "AD_CREATIVE_AUTO_DERIVE"
	AdCreativeSource_AUTO_GENERATE    AdCreativeSource = "AD_CREATIVE_AUTO_GENERATE"
	AdCreativeSource_PAGE_DERIVE      AdCreativeSource = "AD_CREATIVE_PAGE_DERIVE"
	AdCreativeSource_SEARCH_EXPANSION AdCreativeSource = "AD_CREATIVE_SEARCH_EXPANSION"
)
