/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 预算维度的曝光评估结果
type CostDiagnosisConclusionSpec struct {
	CostDiagnosisScore             int64  `json:"cost_diagnosis_score,omitempty"`
	Balance                        int64  `json:"balance,omitempty"`
	AdDailyBudget                  int64  `json:"ad_daily_budget,omitempty"`
	AdRealtimeAvailableBudget      int64  `json:"ad_realtime_available_budget,omitempty"`
	AdCost                         int64  `json:"ad_cost,omitempty"`
	CampainDailyBudget             int64  `json:"campain_daily_budget,omitempty"`
	CampainCost                    int64  `json:"campain_cost,omitempty"`
	CampainRealtimeAvailableBudget int64  `json:"campain_realtime_available_budget,omitempty"`
	AccountDailyBudget             int64  `json:"account_daily_budget,omitempty"`
	AccountCost                    int64  `json:"account_cost,omitempty"`
	AccountRealtimeAvailableBudget int64  `json:"account_realtime_available_budget,omitempty"`
	Conclusion                     string `json:"conclusion,omitempty"`
}
