/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 附近推微信账户更多信息
type LocalWechatFundSpec struct {
	CashUsableAmount *int64 `json:"cash_usable_amount,omitempty"`
	GiftUsableAmount *int64 `json:"gift_usable_amount,omitempty"`
	CashLockedAmount *int64 `json:"cash_locked_amount,omitempty"`
	GiftLockedAmount *int64 `json:"gift_locked_amount,omitempty"`
}
