/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// SiteSetDefinition : 版位信息
type SiteSetDefinition string

// List of SiteSetDefinition
const (
	SiteSetDefinition_QZONE                      SiteSetDefinition = "SITE_SET_QZONE"
	SiteSetDefinition_QQCLIENT                   SiteSetDefinition = "SITE_SET_QQCLIENT"
	SiteSetDefinition_MUSIC                      SiteSetDefinition = "SITE_SET_MUSIC"
	SiteSetDefinition_MOBILE_UNION               SiteSetDefinition = "SITE_SET_MOBILE_UNION"
	SiteSetDefinition_QQCOM                      SiteSetDefinition = "SITE_SET_QQCOM"
	SiteSetDefinition_WECHAT                     SiteSetDefinition = "SITE_SET_WECHAT"
	SiteSetDefinition_MOBILE_MYAPP               SiteSetDefinition = "SITE_SET_MOBILE_MYAPP"
	SiteSetDefinition_MOBILE_YYB                 SiteSetDefinition = "SITE_SET_MOBILE_YYB"
	SiteSetDefinition_QQSHOPPING                 SiteSetDefinition = "SITE_SET_QQSHOPPING"
	SiteSetDefinition_MOBILE_INNER               SiteSetDefinition = "SITE_SET_MOBILE_INNER"
	SiteSetDefinition_TENCENT_NEWS               SiteSetDefinition = "SITE_SET_TENCENT_NEWS"
	SiteSetDefinition_TENCENT_VIDEO              SiteSetDefinition = "SITE_SET_TENCENT_VIDEO"
	SiteSetDefinition_TENCENT_KUAIBAO            SiteSetDefinition = "SITE_SET_TENCENT_KUAIBAO"
	SiteSetDefinition_PENGYOU                    SiteSetDefinition = "SITE_SET_PENGYOU"
	SiteSetDefinition_TUAN                       SiteSetDefinition = "SITE_SET_TUAN"
	SiteSetDefinition_MEISHI                     SiteSetDefinition = "SITE_SET_MEISHI"
	SiteSetDefinition_PIAO                       SiteSetDefinition = "SITE_SET_PIAO"
	SiteSetDefinition_MAIL                       SiteSetDefinition = "SITE_SET_MAIL"
	SiteSetDefinition_PC_UNION                   SiteSetDefinition = "SITE_SET_PC_UNION"
	SiteSetDefinition_YINGYONGBAO_PC             SiteSetDefinition = "SITE_SET_YINGYONGBAO_PC"
	SiteSetDefinition_PAIPAISEARCH               SiteSetDefinition = "SITE_SET_PAIPAISEARCH"
	SiteSetDefinition_QQSHOP                     SiteSetDefinition = "SITE_SET_QQSHOP"
	SiteSetDefinition_PAIPAIDAOGOU               SiteSetDefinition = "SITE_SET_PAIPAIDAOGOU"
	SiteSetDefinition_QZONESEARCH                SiteSetDefinition = "SITE_SET_QZONESEARCH"
	SiteSetDefinition_WEBUNION_DELETED           SiteSetDefinition = "SITE_SET_WEBUNION_DELETED"
	SiteSetDefinition_EXPRESSPORTAL              SiteSetDefinition = "SITE_SET_EXPRESSPORTAL"
	SiteSetDefinition_WEIBO                      SiteSetDefinition = "SITE_SET_WEIBO"
	SiteSetDefinition_WANGGOU                    SiteSetDefinition = "SITE_SET_WANGGOU"
	SiteSetDefinition_MOBILE_UNION_DELETED       SiteSetDefinition = "SITE_SET_MOBILE_UNION_DELETED"
	SiteSetDefinition_THIRDPARTY                 SiteSetDefinition = "SITE_SET_THIRDPARTY"
	SiteSetDefinition_JD_WAICAI                  SiteSetDefinition = "SITE_SET_JD_WAICAI"
	SiteSetDefinition_PCQQ                       SiteSetDefinition = "SITE_SET_PCQQ"
	SiteSetDefinition_PCAD                       SiteSetDefinition = "SITE_SET_PCAD"
	SiteSetDefinition_KUAISHOU                   SiteSetDefinition = "SITE_SET_KUAISHOU"
	SiteSetDefinition_KANDIAN                    SiteSetDefinition = "SITE_SET_KANDIAN"
	SiteSetDefinition_QQ_MUSIC_GAME              SiteSetDefinition = "SITE_SET_QQ_MUSIC_GAME"
	SiteSetDefinition_MOMENTS                    SiteSetDefinition = "SITE_SET_MOMENTS"
	SiteSetDefinition_MINI_GAME_WECHAT           SiteSetDefinition = "SITE_SET_MINI_GAME_WECHAT"
	SiteSetDefinition_MINI_GAME_QQ               SiteSetDefinition = "SITE_SET_MINI_GAME_QQ"
	SiteSetDefinition_MOBILE_GAME                SiteSetDefinition = "SITE_SET_MOBILE_GAME"
	SiteSetDefinition_TENCENT_VIDEO_OTT          SiteSetDefinition = "SITE_SET_TENCENT_VIDEO_OTT"
	SiteSetDefinition_CHANNELS                   SiteSetDefinition = "SITE_SET_CHANNELS"
	SiteSetDefinition_OVERSEAS_UNION             SiteSetDefinition = "SITE_SET_OVERSEAS_UNION"
	SiteSetDefinition_WECHAT_SEARCH              SiteSetDefinition = "SITE_SET_WECHAT_SEARCH"
	SiteSetDefinition_WECHAT_PLUGIN              SiteSetDefinition = "SITE_SET_WECHAT_PLUGIN"
	SiteSetDefinition_FREETRADE                  SiteSetDefinition = "SITE_SET_FREETRADE"
	SiteSetDefinition_QBSEARCH                   SiteSetDefinition = "SITE_SET_QBSEARCH"
	SiteSetDefinition_FREETRADE_FINDER           SiteSetDefinition = "SITE_SET_FREETRADE_FINDER"
	SiteSetDefinition_BROWSER_MOBILE             SiteSetDefinition = "SITE_SET_BROWSER_MOBILE"
	SiteSetDefinition_SEARCH_SCENE               SiteSetDefinition = "SITE_SET_SEARCH_SCENE"
	SiteSetDefinition_BROWSER_PC                 SiteSetDefinition = "SITE_SET_BROWSER_PC"
	SiteSetDefinition_CHANNELS_CONTENT_PROMOTION SiteSetDefinition = "SITE_SET_CHANNELS_CONTENT_PROMOTION"
	SiteSetDefinition_FREETRADE_WEAPP            SiteSetDefinition = "SITE_SET_FREETRADE_WEAPP"
	SiteSetDefinition_TENCENT_AD_NETWORK_OVERSEA SiteSetDefinition = "SITE_SET_TENCENT_AD_NETWORK_OVERSEA"
	SiteSetDefinition_FREETRADE_QQ               SiteSetDefinition = "SITE_SET_FREETRADE_QQ"
)
