/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 表单属性
type FormConfigDetailData struct {
	Title      *string `json:"title,omitempty"`
	SubTitle   *string `json:"sub_title,omitempty"`
	SubmitText *string `json:"submit_text,omitempty"`
}
