/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

// 视频组件
type VideoComponentOption struct {
	ComponentId *int64            `json:"component_id,omitempty"`
	Value       *VideoValueStruct `json:"value,omitempty"`
}
