/*
 * Marketing API
 *
 * Marketing API
 *
 * API version: 1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os"

	"github.com/tencentad/marketing-api-go-sdk/pkg/ads"
	"github.com/tencentad/marketing-api-go-sdk/pkg/config"
	"github.com/tencentad/marketing-api-go-sdk/pkg/errors"
)

type PropertyFilesAddExample struct {
	TAds          *ads.SDKClient
	AccessToken   string
	AccountId     int64
	PropertySetId int64
	SessionId     int64
	FileName      string
	File          *os.File
}

func (e *PropertyFilesAddExample) Init() {
	e.AccessToken = "YOUR ACCESS TOKEN"
	e.TAds = ads.Init(&config.SDKConfig{
		AccessToken: e.AccessToken,
		IsDebug:     true,
	})
	e.AccountId = 789
	e.PropertySetId = 789
	e.SessionId = 789
	e.FileName = "fileName_example"
	file, err := os.Open("YOUR FILE PATH")
	if err != nil {
		e.File = file
	}
}

func (e *PropertyFilesAddExample) RunExample() (interface{}, http.Header, error) {
	tads := e.TAds
	// change ctx as needed
	ctx := *tads.Ctx
	return tads.PropertyFiles().Add(ctx, e.AccountId, e.PropertySetId, e.SessionId, e.FileName, e.File)
}

func main() {
	e := &PropertyFilesAddExample{}
	e.Init()
	response, headers, err := e.RunExample()
	if err != nil {
		if resErr, ok := err.(errors.ResponseError); ok {
			errStr, _ := json.Marshal(resErr)
			fmt.Println("Response error:", string(errStr))
		} else {
			fmt.Println("Error:", err)
		}
	}
	fmt.Println("Response data:", response)
	fmt.Println("Headers:", headers)
}
